--[[
********************************************************************************
	Project owner:		RageQuit community
	Project name: 		GTW-RPG
	Developers:   		Mr_Moose

	Source code:		https://github.com/GTWCode/GTW-RPG/
	Bugtracker: 		http://forum.404rq.com/bug-reports/
	Suggestions:		http://forum.404rq.com/mta-servers-development/

	Version:    		Open source
	License:    		BSD 2-Clause
	Status:     		Stable release
********************************************************************************
]]--

-- Commands to animations converter
cmd_anim_map = {
	["handsup"] 		= { "ped", "handsup" },
	["lookaround"] 		= { "dealer", "dealer_idle" },
	["deal1"] 		= { "dealer", "dealer_idle_01" },
	["deal2"] 		= { "dealer", "dealer_idle_02" },
	["deal3"] 		= { "dealer", "dealer_idle_03" },
	["fatidle"] 		= { "fat", "fatidle" },
	["tired"] 		= { "fat", "idle_tired" },
	["mourn"] 		= { "graveyard", "prst_loopa" },
	["cpr"] 		= { "medic", "cpr" },
	["wave"] 		= { "ped", "endchat_03" },
	["lean"] 		= { "smoking", "m_smklean_loop" },
	["sit"] 		= { "ped", "seat_idle" },
	["cower"] 		= { "ped", "cower" },
	["handcower"] 		= { "ped", "handscower" },
	["gum"] 		= { "ped", "gum_eat" },
	["getup"] 		= { "ped", "getup" },
	["getupfront"] 		= { "ped", "getup_front" },
	["chat"] 		= { "ped", "IDLE_chat" },
	["taxiwink"] 		= { "ped", "IDLE_taxi" },
	["turn180"] 		= { "ped", "turn_180" },
	["urp"] 		= { "ped", "facurp" },
	["gumchew"] 		= { "ped", "facgum" },
}

-- All available animations
animations_table = {
	["AIRPORT"] = {
		{ "thrw_barl_thrw", "AIRPORT", "thrw_barl_thrw" },
	},

	["Attractors"] = {
		{ "Stepsit_in", "Attractors", "Stepsit_in" },
		{ "Stepsit_loop", "Attractors", "Stepsit_loop" },
		{ "Stepsit_out", "Attractors", "Stepsit_out" },
	},

	["BAR"] = {
		{ "Barcustom_get", "BAR", "Barcustom_get" },
		{ "Barcustom_loop", "BAR", "Barcustom_loop" },
		{ "Barcustom_order", "BAR", "Barcustom_order" },
		{ "BARman_idle", "BAR", "BARman_idle" },
		{ "Barserve_bottle", "BAR", "Barserve_bottle" },
		{ "Barserve_give", "BAR", "Barserve_give" },
		{ "Barserve_glass", "BAR", "Barserve_glass" },
		{ "Barserve_in", "BAR", "Barserve_in" },
		{ "Barserve_loop", "BAR", "Barserve_loop" },
		{ "Barserve_order", "BAR", "Barserve_order" },
		{ "dnk_stndF_loop", "BAR", "dnk_stndF_loop" },
		{ "dnk_stndM_loop", "BAR", "dnk_stndM_loop" },
	},

	["BASEBALL"] = {
		{ "Bat_1", "BASEBALL", "Bat_1" },
		{ "Bat_2", "BASEBALL", "Bat_2" },
		{ "Bat_3", "BASEBALL", "Bat_3" },
		{ "Bat_4", "BASEBALL", "Bat_4" },
		{ "Bat_block", "BASEBALL", "Bat_block" },
		{ "Bat_Hit_1", "BASEBALL", "Bat_Hit_1" },
		{ "Bat_Hit_2", "BASEBALL", "Bat_Hit_2" },
		{ "Bat_Hit_3", "BASEBALL", "Bat_Hit_3" },
		{ "Bat_IDLE", "BASEBALL", "Bat_IDLE" },
		{ "Bat_M", "BASEBALL", "Bat_M" },
		{ "BAT_PART", "BASEBALL", "BAT_PART" },
	},

	["BD_FIRE"] = {
		{ "BD_Fire1", "BD_FIRE", "BD_Fire1" },
		{ "BD_Fire2", "BD_FIRE", "BD_Fire2" },
		{ "BD_Fire3", "BD_FIRE", "BD_Fire3" },
		{ "BD_GF_Wave", "BD_FIRE", "BD_GF_Wave" },
		{ "BD_Panic_01", "BD_FIRE", "BD_Panic_01" },
		{ "BD_Panic_02", "BD_FIRE", "BD_Panic_02" },
		{ "BD_Panic_03", "BD_FIRE", "BD_Panic_03" },
		{ "BD_Panic_04", "BD_FIRE", "BD_Panic_04" },
		{ "BD_Panic_Loop", "BD_FIRE", "BD_Panic_Loop" },
		{ "Grlfrd_Kiss_03", "BD_FIRE", "Grlfrd_Kiss_03" },
		{ "M_smklean_loop", "BD_FIRE", "M_smklean_loop" },
		{ "Playa_Kiss_03", "BD_FIRE", "Playa_Kiss_03" },
		{ "wash_up", "BD_FIRE", "wash_up" },
	},

	["BEACH"] = {
		{ "bather", "BEACH", "bather" },
		{ "Lay_Bac_Loop", "BEACH", "Lay_Bac_Loop" },
		{ "ParkSit_M_loop", "BEACH", "ParkSit_M_loop" },
		{ "ParkSit_W_loop", "BEACH", "ParkSit_W_loop" },
		{ "SitnWait_loop_W", "BEACH", "SitnWait_loop_W" },
	},

	["benchpress"] = {
		{ "gym_bp_celebrate", "benchpress", "gym_bp_celebrate" },
		{ "gym_bp_down", "benchpress", "gym_bp_down" },
		{ "gym_bp_getoff", "benchpress", "gym_bp_getoff" },
		{ "gym_bp_geton", "benchpress", "gym_bp_geton" },
		{ "gym_bp_up_A", "benchpress", "gym_bp_up_A" },
		{ "gym_bp_up_B", "benchpress", "gym_bp_up_B" },
		{ "gym_bp_up_smooth", "benchpress", "gym_bp_up_smooth" },
	},

	["BF_injection"] = {
		{ "BF_getin_LHS", "BF_injection", "BF_getin_LHS" },
		{ "BF_getin_RHS", "BF_injection", "BF_getin_RHS" },
		{ "BF_getout_LHS", "BF_injection", "BF_getout_LHS" },
		{ "BF_getout_RHS", "BF_injection", "BF_getout_RHS" },
	},

	["BIKED"] = {
		{ "BIKEd_Back", "BIKED", "BIKEd_Back" },
		{ "BIKEd_drivebyFT", "BIKED", "BIKEd_drivebyFT" },
		{ "BIKEd_drivebyLHS", "BIKED", "BIKEd_drivebyLHS" },
		{ "BIKEd_drivebyRHS", "BIKED", "BIKEd_drivebyRHS" },
		{ "BIKEd_Fwd", "BIKED", "BIKEd_Fwd" },
		{ "BIKEd_getoffBACK", "BIKED", "BIKEd_getoffBACK" },
		{ "BIKEd_getoffLHS", "BIKED", "BIKEd_getoffLHS" },
		{ "BIKEd_getoffRHS", "BIKED", "BIKEd_getoffRHS" },
		{ "BIKEd_hit", "BIKED", "BIKEd_hit" },
		{ "BIKEd_jumponL", "BIKED", "BIKEd_jumponL" },
		{ "BIKEd_jumponR", "BIKED", "BIKEd_jumponR" },
		{ "BIKEd_kick", "BIKED", "BIKEd_kick" },
		{ "BIKEd_Left", "BIKED", "BIKEd_Left" },
		{ "BIKEd_passenger", "BIKED", "BIKEd_passenger" },
		{ "BIKEd_pushes", "BIKED", "BIKEd_pushes" },
		{ "BIKEd_Ride", "BIKED", "BIKEd_Ride" },
		{ "BIKEd_Right", "BIKED", "BIKEd_Right" },
		{ "BIKEd_shuffle", "BIKED", "BIKEd_shuffle" },
		{ "BIKEd_Still", "BIKED", "BIKEd_Still" },
	},

	["BIKEH"] = {
		{ "BIKEh_Back", "BIKEH", "BIKEh_Back" },
		{ "BIKEh_drivebyFT", "BIKEH", "BIKEh_drivebyFT" },
		{ "BIKEh_drivebyLHS", "BIKEH", "BIKEh_drivebyLHS" },
		{ "BIKEh_drivebyRHS", "BIKEH", "BIKEh_drivebyRHS" },
		{ "BIKEh_Fwd", "BIKEH", "BIKEh_Fwd" },
		{ "BIKEh_getoffBACK", "BIKEH", "BIKEh_getoffBACK" },
		{ "BIKEh_getoffLHS", "BIKEH", "BIKEh_getoffLHS" },
		{ "BIKEh_getoffRHS", "BIKEH", "BIKEh_getoffRHS" },
		{ "BIKEh_hit", "BIKEH", "BIKEh_hit" },
		{ "BIKEh_jumponL", "BIKEH", "BIKEh_jumponL" },
		{ "BIKEh_jumponR", "BIKEH", "BIKEh_jumponR" },
		{ "BIKEh_kick", "BIKEH", "BIKEh_kick" },
		{ "BIKEh_Left", "BIKEH", "BIKEh_Left" },
		{ "BIKEh_passenger", "BIKEH", "BIKEh_passenger" },
		{ "BIKEh_pushes", "BIKEH", "BIKEh_pushes" },
		{ "BIKEh_Ride", "BIKEH", "BIKEh_Ride" },
		{ "BIKEh_Right", "BIKEH", "BIKEh_Right" },
		{ "BIKEh_Still", "BIKEH", "BIKEh_Still" },
	},

	["BIKELEAP"] = {
		{ "bk_blnce_in", "BIKELEAP", "bk_blnce_in" },
		{ "bk_blnce_out", "BIKELEAP", "bk_blnce_out" },
		{ "bk_jmp", "BIKELEAP", "bk_jmp" },
		{ "bk_rdy_in", "BIKELEAP", "bk_rdy_in" },
		{ "bk_rdy_out", "BIKELEAP", "bk_rdy_out" },
		{ "struggle_cesar", "BIKELEAP", "struggle_cesar" },
		{ "struggle_driver", "BIKELEAP", "struggle_driver" },
		{ "truck_driver", "BIKELEAP", "truck_driver" },
		{ "truck_getin", "BIKELEAP", "truck_getin" },
	},

	["BIKES"] = {
		{ "BIKEs_Back", "BIKES", "BIKEs_Back" },
		{ "BIKEs_drivebyFT", "BIKES", "BIKEs_drivebyFT" },
		{ "BIKEs_drivebyLHS", "BIKES", "BIKEs_drivebyLHS" },
		{ "BIKEs_drivebyRHS", "BIKES", "BIKEs_drivebyRHS" },
		{ "BIKEs_Fwd", "BIKES", "BIKEs_Fwd" },
		{ "BIKEs_getoffBACK", "BIKES", "BIKEs_getoffBACK" },
		{ "BIKEs_getoffLHS", "BIKES", "BIKEs_getoffLHS" },
		{ "BIKEs_getoffRHS", "BIKES", "BIKEs_getoffRHS" },
		{ "BIKEs_hit", "BIKES", "BIKEs_hit" },
		{ "BIKEs_jumponL", "BIKES", "BIKEs_jumponL" },
		{ "BIKEs_jumponR", "BIKES", "BIKEs_jumponR" },
		{ "BIKEs_kick", "BIKES", "BIKEs_kick" },
		{ "BIKEs_Left", "BIKES", "BIKEs_Left" },
		{ "BIKEs_passenger", "BIKES", "BIKEs_passenger" },
		{ "BIKEs_pushes", "BIKES", "BIKEs_pushes" },
		{ "BIKEs_Ride", "BIKES", "BIKEs_Ride" },
		{ "BIKEs_Right", "BIKES", "BIKEs_Right" },
		{ "BIKEs_Snatch_L", "BIKES", "BIKEs_Snatch_L" },
		{ "BIKEs_Snatch_R", "BIKES", "BIKEs_Snatch_R" },
		{ "BIKEs_Still", "BIKES", "BIKEs_Still" },
	},

	["BIKEV"] = {
		{ "BIKEv_Back", "BIKEV", "BIKEv_Back" },
		{ "BIKEv_drivebyFT", "BIKEV", "BIKEv_drivebyFT" },
		{ "BIKEv_drivebyLHS", "BIKEV", "BIKEv_drivebyLHS" },
		{ "BIKEv_drivebyRHS", "BIKEV", "BIKEv_drivebyRHS" },
		{ "BIKEv_Fwd", "BIKEV", "BIKEv_Fwd" },
		{ "BIKEv_getoffBACK", "BIKEV", "BIKEv_getoffBACK" },
		{ "BIKEv_getoffLHS", "BIKEV", "BIKEv_getoffLHS" },
		{ "BIKEv_getoffRHS", "BIKEV", "BIKEv_getoffRHS" },
		{ "BIKEv_hit", "BIKEV", "BIKEv_hit" },
		{ "BIKEv_jumponL", "BIKEV", "BIKEv_jumponL" },
		{ "BIKEv_jumponR", "BIKEV", "BIKEv_jumponR" },
		{ "BIKEv_kick", "BIKEV", "BIKEv_kick" },
		{ "BIKEv_Left", "BIKEV", "BIKEv_Left" },
		{ "BIKEv_passenger", "BIKEV", "BIKEv_passenger" },
		{ "BIKEv_pushes", "BIKEV", "BIKEv_pushes" },
		{ "BIKEv_Ride", "BIKEV", "BIKEv_Ride" },
		{ "BIKEv_Right", "BIKEV", "BIKEv_Right" },
		{ "BIKEv_Still", "BIKEV", "BIKEv_Still" },
	},

	["BIKE_DBZ"] = {
		{ "Pass_Driveby_BWD", "BIKE_DBZ", "Pass_Driveby_BWD" },
		{ "Pass_Driveby_FWD", "BIKE_DBZ", "Pass_Driveby_FWD" },
		{ "Pass_Driveby_LHS", "BIKE_DBZ", "Pass_Driveby_LHS" },
		{ "Pass_Driveby_RHS", "BIKE_DBZ", "Pass_Driveby_RHS" },
	},

	["BMX"] = {
		{ "BMX_back", "BMX", "BMX_back" },
		{ "BMX_bunnyhop", "BMX", "BMX_bunnyhop" },
		{ "BMX_drivebyFT", "BMX", "BMX_drivebyFT" },
		{ "BMX_driveby_LHS", "BMX", "BMX_driveby_LHS" },
		{ "BMX_driveby_RHS", "BMX", "BMX_driveby_RHS" },
		{ "BMX_fwd", "BMX", "BMX_fwd" },
		{ "BMX_getoffBACK", "BMX", "BMX_getoffBACK" },
		{ "BMX_getoffLHS", "BMX", "BMX_getoffLHS" },
		{ "BMX_getoffRHS", "BMX", "BMX_getoffRHS" },
		{ "BMX_jumponL", "BMX", "BMX_jumponL" },
		{ "BMX_jumponR", "BMX", "BMX_jumponR" },
		{ "BMX_Left", "BMX", "BMX_Left" },
		{ "BMX_pedal", "BMX", "BMX_pedal" },
		{ "BMX_pushes", "BMX", "BMX_pushes" },
		{ "BMX_Ride", "BMX", "BMX_Ride" },
		{ "BMX_Right", "BMX", "BMX_Right" },
		{ "BMX_sprint", "BMX", "BMX_sprint" },
		{ "BMX_still", "BMX", "BMX_still" },
	},

	["BOMBER"] = {
		{ "BOM_Plant", "BOMBER", "BOM_Plant" },
		{ "BOM_Plant_2Idle", "BOMBER", "BOM_Plant_2Idle" },
		{ "BOM_Plant_Crouch_In", "BOMBER", "BOM_Plant_Crouch_In" },
		{ "BOM_Plant_Crouch_Out", "BOMBER", "BOM_Plant_Crouch_Out" },
		{ "BOM_Plant_In", "BOMBER", "BOM_Plant_In" },
		{ "BOM_Plant_Loop", "BOMBER", "BOM_Plant_Loop" },
	},

	["BOX"] = {
		{ "boxhipin", "BOX", "boxhipin" },
		{ "boxhipup", "BOX", "boxhipup" },
		{ "boxshdwn", "BOX", "boxshdwn" },
		{ "boxshup", "BOX", "boxshup" },
		{ "bxhipwlk", "BOX", "bxhipwlk" },
		{ "bxhwlki", "BOX", "bxhwlki" },
		{ "bxshwlk", "BOX", "bxshwlk" },
		{ "bxshwlki", "BOX", "bxshwlki" },
		{ "bxwlko", "BOX", "bxwlko" },
		{ "catch_box", "BOX", "catch_box" },
	},

	["BSKTBALL"] = {
		{ "BBALL_def_jump_shot", "BSKTBALL", "BBALL_def_jump_shot" },
		{ "BBALL_def_loop", "BSKTBALL", "BBALL_def_loop" },
		{ "BBALL_def_stepL", "BSKTBALL", "BBALL_def_stepL" },
		{ "BBALL_def_stepR", "BSKTBALL", "BBALL_def_stepR" },
		{ "BBALL_Dnk", "BSKTBALL", "BBALL_Dnk" },
		{ "BBALL_Dnk_Gli", "BSKTBALL", "BBALL_Dnk_Gli" },
		{ "BBALL_Dnk_Gli_O", "BSKTBALL", "BBALL_Dnk_Gli_O" },
		{ "BBALL_Dnk_Lnch", "BSKTBALL", "BBALL_Dnk_Lnch" },
		{ "BBALL_Dnk_Lnch_O", "BSKTBALL", "BBALL_Dnk_Lnch_O" },
		{ "BBALL_Dnk_Lnd", "BSKTBALL", "BBALL_Dnk_Lnd" },
		{ "BBALL_Dnk_O", "BSKTBALL", "BBALL_Dnk_O" },
		{ "BBALL_idle", "BSKTBALL", "BBALL_idle" },
		{ "BBALL_idle2", "BSKTBALL", "BBALL_idle2" },
		{ "BBALL_idle2_O", "BSKTBALL", "BBALL_idle2_O" },
		{ "BBALL_idleloop", "BSKTBALL", "BBALL_idleloop" },
		{ "BBALL_idleloop_O", "BSKTBALL", "BBALL_idleloop_O" },
		{ "BBALL_idle_O", "BSKTBALL", "BBALL_idle_O" },
		{ "BBALL_Jump_Cancel", "BSKTBALL", "BBALL_Jump_Cancel" },
		{ "BBALL_Jump_Cancel_O", "BSKTBALL", "BBALL_Jump_Cancel_O" },
		{ "BBALL_Jump_End", "BSKTBALL", "BBALL_Jump_End" },
		{ "BBALL_Jump_Shot", "BSKTBALL", "BBALL_Jump_Shot" },
		{ "BBALL_Jump_Shot_O", "BSKTBALL", "BBALL_Jump_Shot_O" },
		{ "BBALL_Net_Dnk_O", "BSKTBALL", "BBALL_Net_Dnk_O" },
		{ "BBALL_pickup", "BSKTBALL", "BBALL_pickup" },
		{ "BBALL_pickup_O", "BSKTBALL", "BBALL_pickup_O" },
		{ "BBALL_react_miss", "BSKTBALL", "BBALL_react_miss" },
		{ "BBALL_react_score", "BSKTBALL", "BBALL_react_score" },
		{ "BBALL_run", "BSKTBALL", "BBALL_run" },
		{ "BBALL_run_O", "BSKTBALL", "BBALL_run_O" },
		{ "BBALL_SkidStop_L", "BSKTBALL", "BBALL_SkidStop_L" },
		{ "BBALL_SkidStop_L_O", "BSKTBALL", "BBALL_SkidStop_L_O" },
		{ "BBALL_SkidStop_R", "BSKTBALL", "BBALL_SkidStop_R" },
		{ "BBALL_SkidStop_R_O", "BSKTBALL", "BBALL_SkidStop_R_O" },
		{ "BBALL_walk", "BSKTBALL", "BBALL_walk" },
		{ "BBALL_WalkStop_L", "BSKTBALL", "BBALL_WalkStop_L" },
		{ "BBALL_WalkStop_L_O", "BSKTBALL", "BBALL_WalkStop_L_O" },
		{ "BBALL_WalkStop_R", "BSKTBALL", "BBALL_WalkStop_R" },
		{ "BBALL_WalkStop_R_O", "BSKTBALL", "BBALL_WalkStop_R_O" },
		{ "BBALL_walk_O", "BSKTBALL", "BBALL_walk_O" },
		{ "BBALL_walk_start", "BSKTBALL", "BBALL_walk_start" },
		{ "BBALL_walk_start_O", "BSKTBALL", "BBALL_walk_start_O" },
	},

	["BUDDY"] = {
		{ "buddy_crouchfire", "BUDDY", "buddy_crouchfire" },
		{ "buddy_crouchreload", "BUDDY", "buddy_crouchreload" },
		{ "buddy_fire", "BUDDY", "buddy_fire" },
		{ "buddy_fire_poor", "BUDDY", "buddy_fire_poor" },
		{ "buddy_reload", "BUDDY", "buddy_reload" },
	},

	["BUS"] = {
		{ "BUS_close", "BUS", "BUS_close" },
		{ "BUS_getin_LHS", "BUS", "BUS_getin_LHS" },
		{ "BUS_getin_RHS", "BUS", "BUS_getin_RHS" },
		{ "BUS_getout_LHS", "BUS", "BUS_getout_LHS" },
		{ "BUS_getout_RHS", "BUS", "BUS_getout_RHS" },
		{ "BUS_jacked_LHS", "BUS", "BUS_jacked_LHS" },
		{ "BUS_open", "BUS", "BUS_open" },
		{ "BUS_open_RHS", "BUS", "BUS_open_RHS" },
		{ "BUS_pullout_LHS", "BUS", "BUS_pullout_LHS" },
	},

	["CAMERA"] = {
		{ "camcrch_cmon", "CAMERA", "camcrch_cmon" },
		{ "camcrch_idleloop", "CAMERA", "camcrch_idleloop" },
		{ "camcrch_stay", "CAMERA", "camcrch_stay" },
		{ "camcrch_to_camstnd", "CAMERA", "camcrch_to_camstnd" },
		{ "camstnd_cmon", "CAMERA", "camstnd_cmon" },
		{ "camstnd_idleloop", "CAMERA", "camstnd_idleloop" },
		{ "camstnd_lkabt", "CAMERA", "camstnd_lkabt" },
		{ "camstnd_to_camcrch", "CAMERA", "camstnd_to_camcrch" },
		{ "piccrch_in", "CAMERA", "piccrch_in" },
		{ "piccrch_out", "CAMERA", "piccrch_out" },
		{ "piccrch_take", "CAMERA", "piccrch_take" },
		{ "picstnd_in", "CAMERA", "picstnd_in" },
		{ "picstnd_out", "CAMERA", "picstnd_out" },
		{ "picstnd_take", "CAMERA", "picstnd_take" },
	},

	["CAR"] = {
		{ "Fixn_Car_Loop", "CAR", "Fixn_Car_Loop" },
		{ "Fixn_Car_Out", "CAR", "Fixn_Car_Out" },
		{ "flag_drop", "CAR", "flag_drop" },
		{ "Sit_relaxed", "CAR", "Sit_relaxed" },
		{ "Tap_hand", "CAR", "Tap_hand" },
		{ "Tyd2car_bump", "CAR", "Tyd2car_bump" },
		{ "Tyd2car_high", "CAR", "Tyd2car_high" },
		{ "Tyd2car_low", "CAR", "Tyd2car_low" },
		{ "Tyd2car_med", "CAR", "Tyd2car_med" },
		{ "Tyd2car_TurnL", "CAR", "Tyd2car_TurnL" },
		{ "Tyd2car_TurnR", "CAR", "Tyd2car_TurnR" },
	},

	["CARRY"] = {
		{ "crry_prtial", "CARRY", "crry_prtial" },
		{ "liftup", "CARRY", "liftup" },
		{ "liftup05", "CARRY", "liftup05" },
		{ "liftup105", "CARRY", "liftup105" },
		{ "putdwn", "CARRY", "putdwn" },
		{ "putdwn05", "CARRY", "putdwn05" },
		{ "putdwn105", "CARRY", "putdwn105" },
	},

	["CAR_CHAT"] = {
		{ "carfone_in", "CAR_CHAT", "carfone_in" },
		{ "carfone_loopA", "CAR_CHAT", "carfone_loopA" },
		{ "carfone_loopA_to_B", "CAR_CHAT", "carfone_loopA_to_B" },
		{ "carfone_loopB", "CAR_CHAT", "carfone_loopB" },
		{ "carfone_loopB_to_A", "CAR_CHAT", "carfone_loopB_to_A" },
		{ "carfone_out", "CAR_CHAT", "carfone_out" },
		{ "CAR_Sc1_BL", "CAR_CHAT", "CAR_Sc1_BL" },
		{ "CAR_Sc1_BR", "CAR_CHAT", "CAR_Sc1_BR" },
		{ "CAR_Sc1_FL", "CAR_CHAT", "CAR_Sc1_FL" },
		{ "CAR_Sc1_FR", "CAR_CHAT", "CAR_Sc1_FR" },
		{ "CAR_Sc2_FL", "CAR_CHAT", "CAR_Sc2_FL" },
		{ "CAR_Sc3_BR", "CAR_CHAT", "CAR_Sc3_BR" },
		{ "CAR_Sc3_FL", "CAR_CHAT", "CAR_Sc3_FL" },
		{ "CAR_Sc3_FR", "CAR_CHAT", "CAR_Sc3_FR" },
		{ "CAR_Sc4_BL", "CAR_CHAT", "CAR_Sc4_BL" },
		{ "CAR_Sc4_BR", "CAR_CHAT", "CAR_Sc4_BR" },
		{ "CAR_Sc4_FL", "CAR_CHAT", "CAR_Sc4_FL" },
		{ "CAR_Sc4_FR", "CAR_CHAT", "CAR_Sc4_FR" },
		{ "car_talkm_in", "CAR_CHAT", "car_talkm_in" },
		{ "car_talkm_loop", "CAR_CHAT", "car_talkm_loop" },
		{ "car_talkm_out", "CAR_CHAT", "car_talkm_out" },
	},

	["CASINO"] = {
		{ "cards_in", "CASINO", "cards_in" },
		{ "cards_loop", "CASINO", "cards_loop" },
		{ "cards_lose", "CASINO", "cards_lose" },
		{ "cards_out", "CASINO", "cards_out" },
		{ "cards_pick_01", "CASINO", "cards_pick_01" },
		{ "cards_pick_02", "CASINO", "cards_pick_02" },
		{ "cards_raise", "CASINO", "cards_raise" },
		{ "cards_win", "CASINO", "cards_win" },
		{ "dealone", "CASINO", "dealone" },
		{ "manwinb", "CASINO", "manwinb" },
		{ "manwind", "CASINO", "manwind" },
		{ "Roulette_bet", "CASINO", "Roulette_bet" },
		{ "Roulette_in", "CASINO", "Roulette_in" },
		{ "Roulette_loop", "CASINO", "Roulette_loop" },
		{ "Roulette_lose", "CASINO", "Roulette_lose" },
		{ "Roulette_out", "CASINO", "Roulette_out" },
		{ "Roulette_win", "CASINO", "Roulette_win" },
		{ "Slot_bet_01", "CASINO", "Slot_bet_01" },
		{ "Slot_bet_02", "CASINO", "Slot_bet_02" },
		{ "Slot_in", "CASINO", "Slot_in" },
		{ "Slot_lose_out", "CASINO", "Slot_lose_out" },
		{ "Slot_Plyr", "CASINO", "Slot_Plyr" },
		{ "Slot_wait", "CASINO", "Slot_wait" },
		{ "Slot_win_out", "CASINO", "Slot_win_out" },
		{ "wof", "CASINO", "wof" },
	},

	["CHAINSAW"] = {
		{ "CSAW_1", "CHAINSAW", "CSAW_1" },
		{ "CSAW_2", "CHAINSAW", "CSAW_2" },
		{ "CSAW_3", "CHAINSAW", "CSAW_3" },
		{ "CSAW_G", "CHAINSAW", "CSAW_G" },
		{ "CSAW_Hit_1", "CHAINSAW", "CSAW_Hit_1" },
		{ "CSAW_Hit_2", "CHAINSAW", "CSAW_Hit_2" },
		{ "CSAW_Hit_3", "CHAINSAW", "CSAW_Hit_3" },
		{ "csaw_part", "CHAINSAW", "csaw_part" },
		{ "IDLE_csaw", "CHAINSAW", "IDLE_csaw" },
		{ "WEAPON_csaw", "CHAINSAW", "WEAPON_csaw" },
		{ "WEAPON_csawlo", "CHAINSAW", "WEAPON_csawlo" },
	},

	["CHOPPA"] = {
		{ "CHOPPA_back", "CHOPPA", "CHOPPA_back" },
		{ "CHOPPA_bunnyhop", "CHOPPA", "CHOPPA_bunnyhop" },
		{ "CHOPPA_drivebyFT", "CHOPPA", "CHOPPA_drivebyFT" },
		{ "CHOPPA_driveby_LHS", "CHOPPA", "CHOPPA_driveby_LHS" },
		{ "CHOPPA_driveby_RHS", "CHOPPA", "CHOPPA_driveby_RHS" },
		{ "CHOPPA_fwd", "CHOPPA", "CHOPPA_fwd" },
		{ "CHOPPA_getoffBACK", "CHOPPA", "CHOPPA_getoffBACK" },
		{ "CHOPPA_getoffLHS", "CHOPPA", "CHOPPA_getoffLHS" },
		{ "CHOPPA_getoffRHS", "CHOPPA", "CHOPPA_getoffRHS" },
		{ "CHOPPA_jumponL", "CHOPPA", "CHOPPA_jumponL" },
		{ "CHOPPA_jumponR", "CHOPPA", "CHOPPA_jumponR" },
		{ "CHOPPA_Left", "CHOPPA", "CHOPPA_Left" },
		{ "CHOPPA_pedal", "CHOPPA", "CHOPPA_pedal" },
		{ "CHOPPA_Pushes", "CHOPPA", "CHOPPA_Pushes" },
		{ "CHOPPA_ride", "CHOPPA", "CHOPPA_ride" },
		{ "CHOPPA_Right", "CHOPPA", "CHOPPA_Right" },
		{ "CHOPPA_sprint", "CHOPPA", "CHOPPA_sprint" },
		{ "CHOPPA_Still", "CHOPPA", "CHOPPA_Still" },
	},

	["CLOTHES"] = {
		{ "CLO_Buy", "CLOTHES", "CLO_Buy" },
		{ "CLO_In", "CLOTHES", "CLO_In" },
		{ "CLO_Out", "CLOTHES", "CLO_Out" },
		{ "CLO_Pose_Hat", "CLOTHES", "CLO_Pose_Hat" },
		{ "CLO_Pose_In", "CLOTHES", "CLO_Pose_In" },
		{ "CLO_Pose_In_O", "CLOTHES", "CLO_Pose_In_O" },
		{ "CLO_Pose_Legs", "CLOTHES", "CLO_Pose_Legs" },
		{ "CLO_Pose_Loop", "CLOTHES", "CLO_Pose_Loop" },
		{ "CLO_Pose_Out", "CLOTHES", "CLO_Pose_Out" },
		{ "CLO_Pose_Out_O", "CLOTHES", "CLO_Pose_Out_O" },
		{ "CLO_Pose_Shoes", "CLOTHES", "CLO_Pose_Shoes" },
		{ "CLO_Pose_Torso", "CLOTHES", "CLO_Pose_Torso" },
		{ "CLO_Pose_Watch", "CLOTHES", "CLO_Pose_Watch" },
	},

	["COACH"] = {
		{ "COACH_inL", "COACH", "COACH_inL" },
		{ "COACH_inR", "COACH", "COACH_inR" },
		{ "COACH_opnL", "COACH", "COACH_opnL" },
		{ "COACH_opnR", "COACH", "COACH_opnR" },
		{ "COACH_outL", "COACH", "COACH_outL" },
		{ "COACH_outR", "COACH", "COACH_outR" },
	},

	["COLT45"] = {
		{ "2guns_crouchfire", "COLT45", "2guns_crouchfire" },
		{ "colt45_crouchfire", "COLT45", "colt45_crouchfire" },
		{ "colt45_crouchreload", "COLT45", "colt45_crouchreload" },
		{ "colt45_fire", "COLT45", "colt45_fire" },
		{ "colt45_fire_2hands", "COLT45", "colt45_fire_2hands" },
		{ "colt45_reload", "COLT45", "colt45_reload" },
		{ "sawnoff_reload", "COLT45", "sawnoff_reload" },
	},

	["COP_AMBIENT"] = {
		{ "Copbrowse_in", "COP_AMBIENT", "Copbrowse_in" },
		{ "Copbrowse_loop", "COP_AMBIENT", "Copbrowse_loop" },
		{ "Copbrowse_nod", "COP_AMBIENT", "Copbrowse_nod" },
		{ "Copbrowse_out", "COP_AMBIENT", "Copbrowse_out" },
		{ "Copbrowse_shake", "COP_AMBIENT", "Copbrowse_shake" },
		{ "Coplook_in", "COP_AMBIENT", "Coplook_in" },
		{ "Coplook_loop", "COP_AMBIENT", "Coplook_loop" },
		{ "Coplook_nod", "COP_AMBIENT", "Coplook_nod" },
		{ "Coplook_out", "COP_AMBIENT", "Coplook_out" },
		{ "Coplook_shake", "COP_AMBIENT", "Coplook_shake" },
		{ "Coplook_think", "COP_AMBIENT", "Coplook_think" },
		{ "Coplook_watch", "COP_AMBIENT", "Coplook_watch" },
	},

	["COP_DVBYZ"] = {
		{ "COP_Dvby_B", "COP_DVBYZ", "COP_Dvby_B" },
		{ "COP_Dvby_FT", "COP_DVBYZ", "COP_Dvby_FT" },
		{ "COP_Dvby_L", "COP_DVBYZ", "COP_Dvby_L" },
		{ "COP_Dvby_R", "COP_DVBYZ", "COP_Dvby_R" },
	},

	["CRACK"] = {
		{ "Bbalbat_Idle_01", "CRACK", "Bbalbat_Idle_01" },
		{ "Bbalbat_Idle_02", "CRACK", "Bbalbat_Idle_02" },
		{ "crckdeth1", "CRACK", "crckdeth1" },
		{ "crckdeth2", "CRACK", "crckdeth2" },
		{ "crckdeth3", "CRACK", "crckdeth3" },
		{ "crckdeth4", "CRACK", "crckdeth4" },
		{ "crckidle1", "CRACK", "crckidle1" },
		{ "crckidle2", "CRACK", "crckidle2" },
		{ "crckidle3", "CRACK", "crckidle3" },
		{ "crckidle4", "CRACK", "crckidle4" },
	},

	["CRIB"] = {
		{ "CRIB_Console_Loop", "CRIB", "CRIB_Console_Loop" },
		{ "CRIB_Use_Switch", "CRIB", "CRIB_Use_Switch" },
		{ "PED_Console_Loop", "CRIB", "PED_Console_Loop" },
		{ "PED_Console_Loose", "CRIB", "PED_Console_Loose" },
		{ "PED_Console_Win", "CRIB", "PED_Console_Win" },
	},

	["DAM_JUMP"] = {
		{ "DAM_Dive_Loop", "DAM_JUMP", "DAM_Dive_Loop" },
		{ "DAM_Land", "DAM_JUMP", "DAM_Land" },
		{ "DAM_Launch", "DAM_JUMP", "DAM_Launch" },
		{ "Jump_Roll", "DAM_JUMP", "Jump_Roll" },
		{ "SF_JumpWall", "DAM_JUMP", "SF_JumpWall" },
	},

	["DANCING"] = {
		{ "bd_clap", "DANCING", "bd_clap" },
		{ "bd_clap1", "DANCING", "bd_clap1" },
		{ "dance_loop", "DANCING", "dance_loop" },
		{ "DAN_Down_A", "DANCING", "DAN_Down_A" },
		{ "DAN_Left_A", "DANCING", "DAN_Left_A" },
		{ "DAN_Loop_A", "DANCING", "DAN_Loop_A" },
		{ "DAN_Right_A", "DANCING", "DAN_Right_A" },
		{ "DAN_Up_A", "DANCING", "DAN_Up_A" },
		{ "dnce_M_a", "DANCING", "dnce_M_a" },
		{ "dnce_M_b", "DANCING", "dnce_M_b" },
		{ "dnce_M_c", "DANCING", "dnce_M_c" },
		{ "dnce_M_d", "DANCING", "dnce_M_d" },
		{ "dnce_M_e", "DANCING", "dnce_M_e" },
	},

	["DEALER"] = {
		{ "DEALER_DEAL", "DEALER", "DEALER_DEAL" },
		{ "DEALER_IDLE", "DEALER", "DEALER_IDLE" },
		{ "DEALER_IDLE_01", "DEALER", "DEALER_IDLE_01" },
		{ "DEALER_IDLE_02", "DEALER", "DEALER_IDLE_02" },
		{ "DEALER_IDLE_03", "DEALER", "DEALER_IDLE_03" },
		{ "DRUGS_BUY", "DEALER", "DRUGS_BUY" },
		{ "shop_pay", "DEALER", "shop_pay" },
	},

	["DILDO"] = {
		{ "DILDO_1", "DILDO", "DILDO_1" },
		{ "DILDO_2", "DILDO", "DILDO_2" },
		{ "DILDO_3", "DILDO", "DILDO_3" },
		{ "DILDO_block", "DILDO", "DILDO_block" },
		{ "DILDO_G", "DILDO", "DILDO_G" },
		{ "DILDO_Hit_1", "DILDO", "DILDO_Hit_1" },
		{ "DILDO_Hit_2", "DILDO", "DILDO_Hit_2" },
		{ "DILDO_Hit_3", "DILDO", "DILDO_Hit_3" },
		{ "DILDO_IDLE", "DILDO", "DILDO_IDLE" },
	},

	["DODGE"] = {
		{ "Cover_Dive_01", "DODGE", "Cover_Dive_01" },
		{ "Cover_Dive_02", "DODGE", "Cover_Dive_02" },
		{ "Crushed", "DODGE", "Crushed" },
		{ "Crush_Jump", "DODGE", "Crush_Jump" },
	},

	["DOZER"] = {
		{ "DOZER_Align_LHS", "DOZER", "DOZER_Align_LHS" },
		{ "DOZER_Align_RHS", "DOZER", "DOZER_Align_RHS" },
		{ "DOZER_getin_LHS", "DOZER", "DOZER_getin_LHS" },
		{ "DOZER_getin_RHS", "DOZER", "DOZER_getin_RHS" },
		{ "DOZER_getout_LHS", "DOZER", "DOZER_getout_LHS" },
		{ "DOZER_getout_RHS", "DOZER", "DOZER_getout_RHS" },
		{ "DOZER_Jacked_LHS", "DOZER", "DOZER_Jacked_LHS" },
		{ "DOZER_Jacked_RHS", "DOZER", "DOZER_Jacked_RHS" },
		{ "DOZER_pullout_LHS", "DOZER", "DOZER_pullout_LHS" },
		{ "DOZER_pullout_RHS", "DOZER", "DOZER_pullout_RHS" },
	},

	["DRIVEBYS"] = {
		{ "Gang_DrivebyLHS", "DRIVEBYS", "Gang_DrivebyLHS" },
		{ "Gang_DrivebyLHS_Bwd", "DRIVEBYS", "Gang_DrivebyLHS_Bwd" },
		{ "Gang_DrivebyLHS_Fwd", "DRIVEBYS", "Gang_DrivebyLHS_Fwd" },
		{ "Gang_DrivebyRHS", "DRIVEBYS", "Gang_DrivebyRHS" },
		{ "Gang_DrivebyRHS_Bwd", "DRIVEBYS", "Gang_DrivebyRHS_Bwd" },
		{ "Gang_DrivebyRHS_Fwd", "DRIVEBYS", "Gang_DrivebyRHS_Fwd" },
		{ "Gang_DrivebyTop_LHS", "DRIVEBYS", "Gang_DrivebyTop_LHS" },
		{ "Gang_DrivebyTop_RHS", "DRIVEBYS", "Gang_DrivebyTop_RHS" },
	},

	["FAT"] = {
		{ "FatIdle", "FAT", "FatIdle" },
		{ "FatIdle_armed", "FAT", "FatIdle_armed" },
		{ "FatIdle_Csaw", "FAT", "FatIdle_Csaw" },
		{ "FatIdle_Rocket", "FAT", "FatIdle_Rocket" },
		{ "FatRun", "FAT", "FatRun" },
		{ "FatRun_armed", "FAT", "FatRun_armed" },
		{ "FatRun_Csaw", "FAT", "FatRun_Csaw" },
		{ "FatRun_Rocket", "FAT", "FatRun_Rocket" },
		{ "FatSprint", "FAT", "FatSprint" },
		{ "FatWalk", "FAT", "FatWalk" },
		{ "FatWalkstart", "FAT", "FatWalkstart" },
		{ "FatWalkstart_Csaw", "FAT", "FatWalkstart_Csaw" },
		{ "FatWalkSt_armed", "FAT", "FatWalkSt_armed" },
		{ "FatWalkSt_Rocket", "FAT", "FatWalkSt_Rocket" },
		{ "FatWalk_armed", "FAT", "FatWalk_armed" },
		{ "FatWalk_Csaw", "FAT", "FatWalk_Csaw" },
		{ "FatWalk_Rocket", "FAT", "FatWalk_Rocket" },
		{ "IDLE_tired", "FAT", "IDLE_tired" },
	},

	["FIGHT_B"] = {
		{ "FightB_1", "FIGHT_B", "FightB_1" },
		{ "FightB_2", "FIGHT_B", "FightB_2" },
		{ "FightB_3", "FIGHT_B", "FightB_3" },
		{ "FightB_block", "FIGHT_B", "FightB_block" },
		{ "FightB_G", "FIGHT_B", "FightB_G" },
		{ "FightB_IDLE", "FIGHT_B", "FightB_IDLE" },
		{ "FightB_M", "FIGHT_B", "FightB_M" },
		{ "HitB_1", "FIGHT_B", "HitB_1" },
		{ "HitB_2", "FIGHT_B", "HitB_2" },
		{ "HitB_3", "FIGHT_B", "HitB_3" },
	},

	["FIGHT_C"] = {
		{ "FightC_1", "FIGHT_C", "FightC_1" },
		{ "FightC_2", "FIGHT_C", "FightC_2" },
		{ "FightC_3", "FIGHT_C", "FightC_3" },
		{ "FightC_block", "FIGHT_C", "FightC_block" },
		{ "FightC_blocking", "FIGHT_C", "FightC_blocking" },
		{ "FightC_G", "FIGHT_C", "FightC_G" },
		{ "FightC_IDLE", "FIGHT_C", "FightC_IDLE" },
		{ "FightC_M", "FIGHT_C", "FightC_M" },
		{ "FightC_Spar", "FIGHT_C", "FightC_Spar" },
		{ "HitC_1", "FIGHT_C", "HitC_1" },
		{ "HitC_2", "FIGHT_C", "HitC_2" },
		{ "HitC_3", "FIGHT_C", "HitC_3" },
	},

	["FIGHT_D"] = {
		{ "FightD_1", "FIGHT_D", "FightD_1" },
		{ "FightD_2", "FIGHT_D", "FightD_2" },
		{ "FightD_3", "FIGHT_D", "FightD_3" },
		{ "FightD_block", "FIGHT_D", "FightD_block" },
		{ "FightD_G", "FIGHT_D", "FightD_G" },
		{ "FightD_IDLE", "FIGHT_D", "FightD_IDLE" },
		{ "FightD_M", "FIGHT_D", "FightD_M" },
		{ "HitD_1", "FIGHT_D", "HitD_1" },
		{ "HitD_2", "FIGHT_D", "HitD_2" },
		{ "HitD_3", "FIGHT_D", "HitD_3" },
	},

	["FIGHT_E"] = {
		{ "FightKick", "FIGHT_E", "FightKick" },
		{ "FightKick_B", "FIGHT_E", "FightKick_B" },
		{ "Hit_fightkick", "FIGHT_E", "Hit_fightkick" },
		{ "Hit_fightkick_B", "FIGHT_E", "Hit_fightkick_B" },
	},

	["FINALE"] = {
		{ "FIN_Climb_In", "FINALE", "FIN_Climb_In" },
		{ "FIN_Cop1_ClimbOut2", "FINALE", "FIN_Cop1_ClimbOut2" },
		{ "FIN_Cop1_Loop", "FINALE", "FIN_Cop1_Loop" },
		{ "FIN_Cop1_Stomp", "FINALE", "FIN_Cop1_Stomp" },
		{ "FIN_Hang_L", "FINALE", "FIN_Hang_L" },
		{ "FIN_Hang_Loop", "FINALE", "FIN_Hang_Loop" },
		{ "FIN_Hang_R", "FINALE", "FIN_Hang_R" },
		{ "FIN_Hang_Slip", "FINALE", "FIN_Hang_Slip" },
		{ "FIN_Jump_On", "FINALE", "FIN_Jump_On" },
		{ "FIN_Land_Car", "FINALE", "FIN_Land_Car" },
		{ "FIN_Land_Die", "FINALE", "FIN_Land_Die" },
		{ "FIN_LegsUp", "FINALE", "FIN_LegsUp" },
		{ "FIN_LegsUp_L", "FINALE", "FIN_LegsUp_L" },
		{ "FIN_LegsUp_Loop", "FINALE", "FIN_LegsUp_Loop" },
		{ "FIN_LegsUp_R", "FINALE", "FIN_LegsUp_R" },
		{ "FIN_Let_Go", "FINALE", "FIN_Let_Go" },
	},

	["FINALE2"] = {
		{ "FIN_Cop1_ClimbOut", "FINALE2", "FIN_Cop1_ClimbOut" },
		{ "FIN_Cop1_Fall", "FINALE2", "FIN_Cop1_Fall" },
		{ "FIN_Cop1_Loop", "FINALE2", "FIN_Cop1_Loop" },
		{ "FIN_Cop1_Shot", "FINALE2", "FIN_Cop1_Shot" },
		{ "FIN_Cop1_Swing", "FINALE2", "FIN_Cop1_Swing" },
		{ "FIN_Cop2_ClimbOut", "FINALE2", "FIN_Cop2_ClimbOut" },
		{ "FIN_Switch_P", "FINALE2", "FIN_Switch_P" },
		{ "FIN_Switch_S", "FINALE2", "FIN_Switch_S" },
	},

	["FLAME"] = {
		{ "FLAME_fire", "FLAME", "FLAME_fire" },
	},

	["Flowers"] = {
		{ "Flower_attack", "Flowers", "Flower_attack" },
		{ "Flower_attack_M", "Flowers", "Flower_attack_M" },
		{ "Flower_Hit", "Flowers", "Flower_Hit" },
	},

	["FOOD"] = {
		{ "EAT_Burger", "FOOD", "EAT_Burger" },
		{ "EAT_Chicken", "FOOD", "EAT_Chicken" },
		{ "EAT_Pizza", "FOOD", "EAT_Pizza" },
		{ "EAT_Vomit_P", "FOOD", "EAT_Vomit_P" },
		{ "EAT_Vomit_SK", "FOOD", "EAT_Vomit_SK" },
		{ "FF_Dam_Bkw", "FOOD", "FF_Dam_Bkw" },
		{ "FF_Dam_Fwd", "FOOD", "FF_Dam_Fwd" },
		{ "FF_Dam_Left", "FOOD", "FF_Dam_Left" },
		{ "FF_Dam_Right", "FOOD", "FF_Dam_Right" },
		{ "FF_Die_Bkw", "FOOD", "FF_Die_Bkw" },
		{ "FF_Die_Fwd", "FOOD", "FF_Die_Fwd" },
		{ "FF_Die_Left", "FOOD", "FF_Die_Left" },
		{ "FF_Die_Right", "FOOD", "FF_Die_Right" },
		{ "FF_Sit_Eat1", "FOOD", "FF_Sit_Eat1" },
		{ "FF_Sit_Eat2", "FOOD", "FF_Sit_Eat2" },
		{ "FF_Sit_Eat3", "FOOD", "FF_Sit_Eat3" },
		{ "FF_Sit_In", "FOOD", "FF_Sit_In" },
		{ "FF_Sit_In_L", "FOOD", "FF_Sit_In_L" },
		{ "FF_Sit_In_R", "FOOD", "FF_Sit_In_R" },
		{ "FF_Sit_Look", "FOOD", "FF_Sit_Look" },
		{ "FF_Sit_Loop", "FOOD", "FF_Sit_Loop" },
		{ "FF_Sit_Out_180", "FOOD", "FF_Sit_Out_180" },
		{ "FF_Sit_Out_L_180", "FOOD", "FF_Sit_Out_L_180" },
		{ "FF_Sit_Out_R_180", "FOOD", "FF_Sit_Out_R_180" },
		{ "SHP_Thank", "FOOD", "SHP_Thank" },
		{ "SHP_Tray_In", "FOOD", "SHP_Tray_In" },
		{ "SHP_Tray_Lift", "FOOD", "SHP_Tray_Lift" },
		{ "SHP_Tray_Lift_In", "FOOD", "SHP_Tray_Lift_In" },
		{ "SHP_Tray_Lift_Loop", "FOOD", "SHP_Tray_Lift_Loop" },
		{ "SHP_Tray_Lift_Out", "FOOD", "SHP_Tray_Lift_Out" },
		{ "SHP_Tray_Out", "FOOD", "SHP_Tray_Out" },
		{ "SHP_Tray_Pose", "FOOD", "SHP_Tray_Pose" },
		{ "SHP_Tray_Return", "FOOD", "SHP_Tray_Return" },
	},

	["Freeweights"] = {
		{ "gym_barbell", "Freeweights", "gym_barbell" },
		{ "gym_free_A", "Freeweights", "gym_free_A" },
		{ "gym_free_B", "Freeweights", "gym_free_B" },
		{ "gym_free_celebrate", "Freeweights", "gym_free_celebrate" },
		{ "gym_free_down", "Freeweights", "gym_free_down" },
		{ "gym_free_loop", "Freeweights", "gym_free_loop" },
		{ "gym_free_pickup", "Freeweights", "gym_free_pickup" },
		{ "gym_free_putdown", "Freeweights", "gym_free_putdown" },
		{ "gym_free_up_smooth", "Freeweights", "gym_free_up_smooth" },
	},

	["GANGS"] = {
		{ "DEALER_DEAL", "GANGS", "DEALER_DEAL" },
		{ "DEALER_IDLE", "GANGS", "DEALER_IDLE" },
		{ "drnkbr_prtl", "GANGS", "drnkbr_prtl" },
		{ "drnkbr_prtl_F", "GANGS", "drnkbr_prtl_F" },
		{ "DRUGS_BUY", "GANGS", "DRUGS_BUY" },
		{ "hndshkaa", "GANGS", "hndshkaa" },
		{ "hndshkba", "GANGS", "hndshkba" },
		{ "hndshkca", "GANGS", "hndshkca" },
		{ "hndshkcb", "GANGS", "hndshkcb" },
		{ "hndshkda", "GANGS", "hndshkda" },
		{ "hndshkea", "GANGS", "hndshkea" },
		{ "hndshkfa", "GANGS", "hndshkfa" },
		{ "hndshkfa_swt", "GANGS", "hndshkfa_swt" },
		{ "Invite_No", "GANGS", "Invite_No" },
		{ "Invite_Yes", "GANGS", "Invite_Yes" },
		{ "leanIDLE", "GANGS", "leanIDLE" },
		{ "leanIN", "GANGS", "leanIN" },
		{ "leanOUT", "GANGS", "leanOUT" },
		{ "prtial_gngtlkA", "GANGS", "prtial_gngtlkA" },
		{ "prtial_gngtlkB", "GANGS", "prtial_gngtlkB" },
		{ "prtial_gngtlkC", "GANGS", "prtial_gngtlkC" },
		{ "prtial_gngtlkD", "GANGS", "prtial_gngtlkD" },
		{ "prtial_gngtlkE", "GANGS", "prtial_gngtlkE" },
		{ "prtial_gngtlkF", "GANGS", "prtial_gngtlkF" },
		{ "prtial_gngtlkG", "GANGS", "prtial_gngtlkG" },
		{ "prtial_gngtlkH", "GANGS", "prtial_gngtlkH" },
		{ "prtial_hndshk_01", "GANGS", "prtial_hndshk_01" },
		{ "prtial_hndshk_biz_01", "GANGS", "prtial_hndshk_biz_01" },
		{ "shake_cara", "GANGS", "shake_cara" },
		{ "shake_carK", "GANGS", "shake_carK" },
		{ "shake_carSH", "GANGS", "shake_carSH" },
		{ "smkcig_prtl", "GANGS", "smkcig_prtl" },
		{ "smkcig_prtl_F", "GANGS", "smkcig_prtl_F" },
	},

	["GHANDS"] = {
		{ "gsign1", "GHANDS", "gsign1" },
		{ "gsign1LH", "GHANDS", "gsign1LH" },
		{ "gsign2", "GHANDS", "gsign2" },
		{ "gsign2LH", "GHANDS", "gsign2LH" },
		{ "gsign3", "GHANDS", "gsign3" },
		{ "gsign3LH", "GHANDS", "gsign3LH" },
		{ "gsign4", "GHANDS", "gsign4" },
		{ "gsign4LH", "GHANDS", "gsign4LH" },
		{ "gsign5", "GHANDS", "gsign5" },
		{ "gsign5LH", "GHANDS", "gsign5LH" },
		{ "LHGsign1", "GHANDS", "LHGsign1" },
		{ "LHGsign2", "GHANDS", "LHGsign2" },
		{ "LHGsign3", "GHANDS", "LHGsign3" },
		{ "LHGsign4", "GHANDS", "LHGsign4" },
		{ "LHGsign5", "GHANDS", "LHGsign5" },
		{ "RHGsign1", "GHANDS", "RHGsign1" },
		{ "RHGsign2", "GHANDS", "RHGsign2" },
		{ "RHGsign3", "GHANDS", "RHGsign3" },
		{ "RHGsign4", "GHANDS", "RHGsign4" },
		{ "RHGsign5", "GHANDS", "RHGsign5" },
	},

	["GHETTO_DB"] = {
		{ "GDB_Car2_PLY", "GHETTO_DB", "GDB_Car2_PLY" },
		{ "GDB_Car2_SMO", "GHETTO_DB", "GDB_Car2_SMO" },
		{ "GDB_Car2_SWE", "GHETTO_DB", "GDB_Car2_SWE" },
		{ "GDB_Car_PLY", "GHETTO_DB", "GDB_Car_PLY" },
		{ "GDB_Car_RYD", "GHETTO_DB", "GDB_Car_RYD" },
		{ "GDB_Car_SMO", "GHETTO_DB", "GDB_Car_SMO" },
		{ "GDB_Car_SWE", "GHETTO_DB", "GDB_Car_SWE" },
	},

	["goggles"] = {
		{ "goggles_put_on", "goggles", "goggles_put_on" },
	},

	["GRAFFITI"] = {
		{ "graffiti_Chkout", "GRAFFITI", "graffiti_Chkout" },
		{ "spraycan_fire", "GRAFFITI", "spraycan_fire" },
	},

	["GRAVEYARD"] = {
		{ "mrnF_loop", "GRAVEYARD", "mrnF_loop" },
		{ "mrnM_loop", "GRAVEYARD", "mrnM_loop" },
		{ "prst_loopa", "GRAVEYARD", "prst_loopa" },
	},

	["GRENADE"] = {
		{ "WEAPON_start_throw", "GRENADE", "WEAPON_start_throw" },
		{ "WEAPON_throw", "GRENADE", "WEAPON_throw" },
		{ "WEAPON_throwu", "GRENADE", "WEAPON_throwu" },
	},

	["GYMNASIUM"] = {
		{ "GYMshadowbox", "GYMNASIUM", "GYMshadowbox" },
		{ "gym_bike_celebrate", "GYMNASIUM", "gym_bike_celebrate" },
		{ "gym_bike_fast", "GYMNASIUM", "gym_bike_fast" },
		{ "gym_bike_faster", "GYMNASIUM", "gym_bike_faster" },
		{ "gym_bike_getoff", "GYMNASIUM", "gym_bike_getoff" },
		{ "gym_bike_geton", "GYMNASIUM", "gym_bike_geton" },
		{ "gym_bike_pedal", "GYMNASIUM", "gym_bike_pedal" },
		{ "gym_bike_slow", "GYMNASIUM", "gym_bike_slow" },
		{ "gym_bike_still", "GYMNASIUM", "gym_bike_still" },
		{ "gym_jog_falloff", "GYMNASIUM", "gym_jog_falloff" },
		{ "gym_shadowbox", "GYMNASIUM", "gym_shadowbox" },
		{ "gym_tread_celebrate", "GYMNASIUM", "gym_tread_celebrate" },
		{ "gym_tread_falloff", "GYMNASIUM", "gym_tread_falloff" },
		{ "gym_tread_getoff", "GYMNASIUM", "gym_tread_getoff" },
		{ "gym_tread_geton", "GYMNASIUM", "gym_tread_geton" },
		{ "gym_tread_jog", "GYMNASIUM", "gym_tread_jog" },
		{ "gym_tread_sprint", "GYMNASIUM", "gym_tread_sprint" },
		{ "gym_tread_tired", "GYMNASIUM", "gym_tread_tired" },
		{ "gym_tread_walk", "GYMNASIUM", "gym_tread_walk" },
		{ "gym_walk_falloff", "GYMNASIUM", "gym_walk_falloff" },
		{ "Pedals_fast", "GYMNASIUM", "Pedals_fast" },
		{ "Pedals_med", "GYMNASIUM", "Pedals_med" },
		{ "Pedals_slow", "GYMNASIUM", "Pedals_slow" },
		{ "Pedals_still", "GYMNASIUM", "Pedals_still" },
	},

	["HAIRCUTS"] = {
		{ "BRB_Beard_01", "HAIRCUTS", "BRB_Beard_01" },
		{ "BRB_Buy", "HAIRCUTS", "BRB_Buy" },
		{ "BRB_Cut", "HAIRCUTS", "BRB_Cut" },
		{ "BRB_Cut_In", "HAIRCUTS", "BRB_Cut_In" },
		{ "BRB_Cut_Out", "HAIRCUTS", "BRB_Cut_Out" },
		{ "BRB_Hair_01", "HAIRCUTS", "BRB_Hair_01" },
		{ "BRB_Hair_02", "HAIRCUTS", "BRB_Hair_02" },
		{ "BRB_In", "HAIRCUTS", "BRB_In" },
		{ "BRB_Loop", "HAIRCUTS", "BRB_Loop" },
		{ "BRB_Out", "HAIRCUTS", "BRB_Out" },
		{ "BRB_Sit_In", "HAIRCUTS", "BRB_Sit_In" },
		{ "BRB_Sit_Loop", "HAIRCUTS", "BRB_Sit_Loop" },
		{ "BRB_Sit_Out", "HAIRCUTS", "BRB_Sit_Out" },
	},

	["HEIST9"] = {
		{ "CAS_G2_GasKO", "HEIST9", "CAS_G2_GasKO" },
		{ "swt_wllpk_L", "HEIST9", "swt_wllpk_L" },
		{ "swt_wllpk_L_back", "HEIST9", "swt_wllpk_L_back" },
		{ "swt_wllpk_R", "HEIST9", "swt_wllpk_R" },
		{ "swt_wllpk_R_back", "HEIST9", "swt_wllpk_R_back" },
		{ "swt_wllshoot_in_L", "HEIST9", "swt_wllshoot_in_L" },
		{ "swt_wllshoot_in_R", "HEIST9", "swt_wllshoot_in_R" },
		{ "swt_wllshoot_out_L", "HEIST9", "swt_wllshoot_out_L" },
		{ "swt_wllshoot_out_R", "HEIST9", "swt_wllshoot_out_R" },
		{ "Use_SwipeCard", "HEIST9", "Use_SwipeCard" },
	},

	["INT_HOUSE"] = {
		{ "BED_In_L", "INT_HOUSE", "BED_In_L" },
		{ "BED_In_R", "INT_HOUSE", "BED_In_R" },
		{ "BED_Loop_L", "INT_HOUSE", "BED_Loop_L" },
		{ "BED_Loop_R", "INT_HOUSE", "BED_Loop_R" },
		{ "BED_Out_L", "INT_HOUSE", "BED_Out_L" },
		{ "BED_Out_R", "INT_HOUSE", "BED_Out_R" },
		{ "LOU_In", "INT_HOUSE", "LOU_In" },
		{ "LOU_Loop", "INT_HOUSE", "LOU_Loop" },
		{ "LOU_Out", "INT_HOUSE", "LOU_Out" },
		{ "wash_up", "INT_HOUSE", "wash_up" },
	},

	["INT_OFFICE"] = {
		{ "FF_Dam_Fwd", "INT_OFFICE", "FF_Dam_Fwd" },
		{ "OFF_Sit_2Idle_180", "INT_OFFICE", "OFF_Sit_2Idle_180" },
		{ "OFF_Sit_Bored_Loop", "INT_OFFICE", "OFF_Sit_Bored_Loop" },
		{ "OFF_Sit_Crash", "INT_OFFICE", "OFF_Sit_Crash" },
		{ "OFF_Sit_Drink", "INT_OFFICE", "OFF_Sit_Drink" },
		{ "OFF_Sit_Idle_Loop", "INT_OFFICE", "OFF_Sit_Idle_Loop" },
		{ "OFF_Sit_In", "INT_OFFICE", "OFF_Sit_In" },
		{ "OFF_Sit_Read", "INT_OFFICE", "OFF_Sit_Read" },
		{ "OFF_Sit_Type_Loop", "INT_OFFICE", "OFF_Sit_Type_Loop" },
		{ "OFF_Sit_Watch", "INT_OFFICE", "OFF_Sit_Watch" },
	},

	["INT_SHOP"] = {
		{ "shop_cashier", "INT_SHOP", "shop_cashier" },
		{ "shop_in", "INT_SHOP", "shop_in" },
		{ "shop_lookA", "INT_SHOP", "shop_lookA" },
		{ "shop_lookB", "INT_SHOP", "shop_lookB" },
		{ "shop_loop", "INT_SHOP", "shop_loop" },
		{ "shop_out", "INT_SHOP", "shop_out" },
		{ "shop_pay", "INT_SHOP", "shop_pay" },
		{ "shop_shelf", "INT_SHOP", "shop_shelf" },
	},

	["JST_BUISNESS"] = {
		{ "girl_01", "JST_BUISNESS", "girl_01" },
		{ "girl_02", "JST_BUISNESS", "girl_02" },
		{ "player_01", "JST_BUISNESS", "player_01" },
		{ "smoke_01", "JST_BUISNESS", "smoke_01" },
	},

	["KART"] = {
		{ "KART_getin_LHS", "KART", "KART_getin_LHS" },
		{ "KART_getin_RHS", "KART", "KART_getin_RHS" },
		{ "KART_getout_LHS", "KART", "KART_getout_LHS" },
		{ "KART_getout_RHS", "KART", "KART_getout_RHS" },
	},

	["KISSING"] = {
		{ "BD_GF_Wave", "KISSING", "BD_GF_Wave" },
		{ "gfwave2", "KISSING", "gfwave2" },
		{ "GF_CarArgue_01", "KISSING", "GF_CarArgue_01" },
		{ "GF_CarArgue_02", "KISSING", "GF_CarArgue_02" },
		{ "GF_CarSpot", "KISSING", "GF_CarSpot" },
		{ "GF_StreetArgue_01", "KISSING", "GF_StreetArgue_01" },
		{ "GF_StreetArgue_02", "KISSING", "GF_StreetArgue_02" },
		{ "gift_get", "KISSING", "gift_get" },
		{ "gift_give", "KISSING", "gift_give" },
		{ "Grlfrd_Kiss_01", "KISSING", "Grlfrd_Kiss_01" },
		{ "Grlfrd_Kiss_02", "KISSING", "Grlfrd_Kiss_02" },
		{ "Grlfrd_Kiss_03", "KISSING", "Grlfrd_Kiss_03" },
		{ "Playa_Kiss_01", "KISSING", "Playa_Kiss_01" },
		{ "Playa_Kiss_02", "KISSING", "Playa_Kiss_02" },
		{ "Playa_Kiss_03", "KISSING", "Playa_Kiss_03" },
	},

	["KNIFE"] = {
		{ "KILL_Knife_Ped_Damage", "KNIFE", "KILL_Knife_Ped_Damage" },
		{ "KILL_Knife_Ped_Die", "KNIFE", "KILL_Knife_Ped_Die" },
		{ "KILL_Knife_Player", "KNIFE", "KILL_Knife_Player" },
		{ "KILL_Partial", "KNIFE", "KILL_Partial" },
		{ "knife_1", "KNIFE", "knife_1" },
		{ "knife_2", "KNIFE", "knife_2" },
		{ "knife_3", "KNIFE", "knife_3" },
		{ "Knife_4", "KNIFE", "Knife_4" },
		{ "knife_block", "KNIFE", "knife_block" },
		{ "Knife_G", "KNIFE", "Knife_G" },
		{ "knife_hit_1", "KNIFE", "knife_hit_1" },
		{ "knife_hit_2", "KNIFE", "knife_hit_2" },
		{ "knife_hit_3", "KNIFE", "knife_hit_3" },
		{ "knife_IDLE", "KNIFE", "knife_IDLE" },
		{ "knife_part", "KNIFE", "knife_part" },
		{ "WEAPON_knifeidle", "KNIFE", "WEAPON_knifeidle" },
	},

	["LAPDAN1"] = {
		{ "LAPDAN_D", "LAPDAN1", "LAPDAN_D" },
		{ "LAPDAN_P", "LAPDAN1", "LAPDAN_P" },
	},

	["LAPDAN2"] = {
		{ "LAPDAN_D", "LAPDAN2", "LAPDAN_D" },
		{ "LAPDAN_P", "LAPDAN2", "LAPDAN_P" },
	},

	["LAPDAN3"] = {
		{ "LAPDAN_D", "LAPDAN3", "LAPDAN_D" },
		{ "LAPDAN_P", "LAPDAN3", "LAPDAN_P" },
	},

	["LOWRIDER"] = {
		{ "F_smklean_loop", "LOWRIDER", "F_smklean_loop" },
		{ "lrgirl_bdbnce", "LOWRIDER", "lrgirl_bdbnce" },
		{ "lrgirl_hair", "LOWRIDER", "lrgirl_hair" },
		{ "lrgirl_hurry", "LOWRIDER", "lrgirl_hurry" },
		{ "lrgirl_idleloop", "LOWRIDER", "lrgirl_idleloop" },
		{ "lrgirl_idle_to_l0", "LOWRIDER", "lrgirl_idle_to_l0" },
		{ "lrgirl_l0_bnce", "LOWRIDER", "lrgirl_l0_bnce" },
		{ "lrgirl_l0_loop", "LOWRIDER", "lrgirl_l0_loop" },
		{ "lrgirl_l0_to_l1", "LOWRIDER", "lrgirl_l0_to_l1" },
		{ "lrgirl_l12_to_l0", "LOWRIDER", "lrgirl_l12_to_l0" },
		{ "lrgirl_l1_bnce", "LOWRIDER", "lrgirl_l1_bnce" },
		{ "lrgirl_l1_loop", "LOWRIDER", "lrgirl_l1_loop" },
		{ "lrgirl_l1_to_l2", "LOWRIDER", "lrgirl_l1_to_l2" },
		{ "lrgirl_l2_bnce", "LOWRIDER", "lrgirl_l2_bnce" },
		{ "lrgirl_l2_loop", "LOWRIDER", "lrgirl_l2_loop" },
		{ "lrgirl_l2_to_l3", "LOWRIDER", "lrgirl_l2_to_l3" },
		{ "lrgirl_l345_to_l1", "LOWRIDER", "lrgirl_l345_to_l1" },
		{ "lrgirl_l3_bnce", "LOWRIDER", "lrgirl_l3_bnce" },
		{ "lrgirl_l3_loop", "LOWRIDER", "lrgirl_l3_loop" },
		{ "lrgirl_l3_to_l4", "LOWRIDER", "lrgirl_l3_to_l4" },
		{ "lrgirl_l4_bnce", "LOWRIDER", "lrgirl_l4_bnce" },
		{ "lrgirl_l4_loop", "LOWRIDER", "lrgirl_l4_loop" },
		{ "lrgirl_l4_to_l5", "LOWRIDER", "lrgirl_l4_to_l5" },
		{ "lrgirl_l5_bnce", "LOWRIDER", "lrgirl_l5_bnce" },
		{ "lrgirl_l5_loop", "LOWRIDER", "lrgirl_l5_loop" },
		{ "M_smklean_loop", "LOWRIDER", "M_smklean_loop" },
		{ "M_smkstnd_loop", "LOWRIDER", "M_smkstnd_loop" },
		{ "prtial_gngtlkB", "LOWRIDER", "prtial_gngtlkB" },
		{ "prtial_gngtlkC", "LOWRIDER", "prtial_gngtlkC" },
		{ "prtial_gngtlkD", "LOWRIDER", "prtial_gngtlkD" },
		{ "prtial_gngtlkE", "LOWRIDER", "prtial_gngtlkE" },
		{ "prtial_gngtlkF", "LOWRIDER", "prtial_gngtlkF" },
		{ "prtial_gngtlkG", "LOWRIDER", "prtial_gngtlkG" },
		{ "prtial_gngtlkH", "LOWRIDER", "prtial_gngtlkH" },
		{ "RAP_A_Loop", "LOWRIDER", "RAP_A_Loop" },
		{ "RAP_B_Loop", "LOWRIDER", "RAP_B_Loop" },
		{ "RAP_C_Loop", "LOWRIDER", "RAP_C_Loop" },
		{ "Sit_relaxed", "LOWRIDER", "Sit_relaxed" },
		{ "Tap_hand", "LOWRIDER", "Tap_hand" },
	},

	["MD_CHASE"] = {
		{ "Carhit_Hangon", "MD_CHASE", "Carhit_Hangon" },
		{ "Carhit_Tumble", "MD_CHASE", "Carhit_Tumble" },
		{ "donutdrop", "MD_CHASE", "donutdrop" },
		{ "Fen_Choppa_L1", "MD_CHASE", "Fen_Choppa_L1" },
		{ "Fen_Choppa_L2", "MD_CHASE", "Fen_Choppa_L2" },
		{ "Fen_Choppa_L3", "MD_CHASE", "Fen_Choppa_L3" },
		{ "Fen_Choppa_R1", "MD_CHASE", "Fen_Choppa_R1" },
		{ "Fen_Choppa_R2", "MD_CHASE", "Fen_Choppa_R2" },
		{ "Fen_Choppa_R3", "MD_CHASE", "Fen_Choppa_R3" },
		{ "Hangon_Stun_loop", "MD_CHASE", "Hangon_Stun_loop" },
		{ "Hangon_Stun_Turn", "MD_CHASE", "Hangon_Stun_Turn" },
		{ "MD_BIKE_2_HANG", "MD_CHASE", "MD_BIKE_2_HANG" },
		{ "MD_BIKE_Jmp_BL", "MD_CHASE", "MD_BIKE_Jmp_BL" },
		{ "MD_BIKE_Jmp_F", "MD_CHASE", "MD_BIKE_Jmp_F" },
		{ "MD_BIKE_Lnd_BL", "MD_CHASE", "MD_BIKE_Lnd_BL" },
		{ "MD_BIKE_Lnd_Die_BL", "MD_CHASE", "MD_BIKE_Lnd_Die_BL" },
		{ "MD_BIKE_Lnd_Die_F", "MD_CHASE", "MD_BIKE_Lnd_Die_F" },
		{ "MD_BIKE_Lnd_F", "MD_CHASE", "MD_BIKE_Lnd_F" },
		{ "MD_BIKE_Lnd_Roll", "MD_CHASE", "MD_BIKE_Lnd_Roll" },
		{ "MD_BIKE_Lnd_Roll_F", "MD_CHASE", "MD_BIKE_Lnd_Roll_F" },
		{ "MD_BIKE_Punch", "MD_CHASE", "MD_BIKE_Punch" },
		{ "MD_BIKE_Punch_F", "MD_CHASE", "MD_BIKE_Punch_F" },
		{ "MD_BIKE_Shot_F", "MD_CHASE", "MD_BIKE_Shot_F" },
		{ "MD_HANG_Lnd_Roll", "MD_CHASE", "MD_HANG_Lnd_Roll" },
		{ "MD_HANG_Loop", "MD_CHASE", "MD_HANG_Loop" },
	},

	["MD_END"] = {
		{ "END_SC1_PLY", "MD_END", "END_SC1_PLY" },
		{ "END_SC1_RYD", "MD_END", "END_SC1_RYD" },
		{ "END_SC1_SMO", "MD_END", "END_SC1_SMO" },
		{ "END_SC1_SWE", "MD_END", "END_SC1_SWE" },
		{ "END_SC2_PLY", "MD_END", "END_SC2_PLY" },
		{ "END_SC2_RYD", "MD_END", "END_SC2_RYD" },
		{ "END_SC2_SMO", "MD_END", "END_SC2_SMO" },
		{ "END_SC2_SWE", "MD_END", "END_SC2_SWE" },
	},

	["MEDIC"] = {
		{ "CPR", "MEDIC", "CPR" },
	},

	["MISC"] = {
		{ "bitchslap", "MISC", "bitchslap" },
		{ "BMX_celebrate", "MISC", "BMX_celebrate" },
		{ "BMX_comeon", "MISC", "BMX_comeon" },
		{ "bmx_idleloop_01", "MISC", "bmx_idleloop_01" },
		{ "bmx_idleloop_02", "MISC", "bmx_idleloop_02" },
		{ "bmx_talkleft_in", "MISC", "bmx_talkleft_in" },
		{ "bmx_talkleft_loop", "MISC", "bmx_talkleft_loop" },
		{ "bmx_talkleft_out", "MISC", "bmx_talkleft_out" },
		{ "bmx_talkright_in", "MISC", "bmx_talkright_in" },
		{ "bmx_talkright_loop", "MISC", "bmx_talkright_loop" },
		{ "bmx_talkright_out", "MISC", "bmx_talkright_out" },
		{ "bng_wndw", "MISC", "bng_wndw" },
		{ "bng_wndw_02", "MISC", "bng_wndw_02" },
		{ "Case_pickup", "MISC", "Case_pickup" },
		{ "door_jet", "MISC", "door_jet" },
		{ "GRAB_L", "MISC", "GRAB_L" },
		{ "GRAB_R", "MISC", "GRAB_R" },
		{ "Hiker_Pose", "MISC", "Hiker_Pose" },
		{ "Hiker_Pose_L", "MISC", "Hiker_Pose_L" },
		{ "Idle_Chat_02", "MISC", "Idle_Chat_02" },
		{ "KAT_Throw_K", "MISC", "KAT_Throw_K" },
		{ "KAT_Throw_O", "MISC", "KAT_Throw_O" },
		{ "KAT_Throw_P", "MISC", "KAT_Throw_P" },
		{ "PASS_Rifle_O", "MISC", "PASS_Rifle_O" },
		{ "PASS_Rifle_Ped", "MISC", "PASS_Rifle_Ped" },
		{ "PASS_Rifle_Ply", "MISC", "PASS_Rifle_Ply" },
		{ "pickup_box", "MISC", "pickup_box" },
		{ "Plane_door", "MISC", "Plane_door" },
		{ "Plane_exit", "MISC", "Plane_exit" },
		{ "Plane_hijack", "MISC", "Plane_hijack" },
		{ "Plunger_01", "MISC", "Plunger_01" },
		{ "Plyrlean_loop", "MISC", "Plyrlean_loop" },
		{ "plyr_shkhead", "MISC", "plyr_shkhead" },
		{ "Run_Dive", "MISC", "Run_Dive" },
		{ "Scratchballs_01", "MISC", "Scratchballs_01" },
		{ "SEAT_LR", "MISC", "SEAT_LR" },
		{ "Seat_talk_01", "MISC", "Seat_talk_01" },
		{ "Seat_talk_02", "MISC", "Seat_talk_02" },
		{ "SEAT_watch", "MISC", "SEAT_watch" },
		{ "smalplane_door", "MISC", "smalplane_door" },
		{ "smlplane_door", "MISC", "smlplane_door" },
	},

	["MTB"] = {
		{ "MTB_back", "MTB", "MTB_back" },
		{ "MTB_bunnyhop", "MTB", "MTB_bunnyhop" },
		{ "MTB_drivebyFT", "MTB", "MTB_drivebyFT" },
		{ "MTB_driveby_LHS", "MTB", "MTB_driveby_LHS" },
		{ "MTB_driveby_RHS", "MTB", "MTB_driveby_RHS" },
		{ "MTB_fwd", "MTB", "MTB_fwd" },
		{ "MTB_getoffBACK", "MTB", "MTB_getoffBACK" },
		{ "MTB_getoffLHS", "MTB", "MTB_getoffLHS" },
		{ "MTB_getoffRHS", "MTB", "MTB_getoffRHS" },
		{ "MTB_jumponL", "MTB", "MTB_jumponL" },
		{ "MTB_jumponR", "MTB", "MTB_jumponR" },
		{ "MTB_Left", "MTB", "MTB_Left" },
		{ "MTB_pedal", "MTB", "MTB_pedal" },
		{ "MTB_pushes", "MTB", "MTB_pushes" },
		{ "MTB_Ride", "MTB", "MTB_Ride" },
		{ "MTB_Right", "MTB", "MTB_Right" },
		{ "MTB_sprint", "MTB", "MTB_sprint" },
		{ "MTB_still", "MTB", "MTB_still" },
	},

	["MUSCULAR"] = {
		{ "MscleWalkst_armed", "MUSCULAR", "MscleWalkst_armed" },
		{ "MscleWalkst_Csaw", "MUSCULAR", "MscleWalkst_Csaw" },
		{ "Mscle_rckt_run", "MUSCULAR", "Mscle_rckt_run" },
		{ "Mscle_rckt_walkst", "MUSCULAR", "Mscle_rckt_walkst" },
		{ "Mscle_run_Csaw", "MUSCULAR", "Mscle_run_Csaw" },
		{ "MuscleIdle", "MUSCULAR", "MuscleIdle" },
		{ "MuscleIdle_armed", "MUSCULAR", "MuscleIdle_armed" },
		{ "MuscleIdle_Csaw", "MUSCULAR", "MuscleIdle_Csaw" },
		{ "MuscleIdle_rocket", "MUSCULAR", "MuscleIdle_rocket" },
		{ "MuscleRun", "MUSCULAR", "MuscleRun" },
		{ "MuscleRun_armed", "MUSCULAR", "MuscleRun_armed" },
		{ "MuscleSprint", "MUSCULAR", "MuscleSprint" },
		{ "MuscleWalk", "MUSCULAR", "MuscleWalk" },
		{ "MuscleWalkstart", "MUSCULAR", "MuscleWalkstart" },
		{ "MuscleWalk_armed", "MUSCULAR", "MuscleWalk_armed" },
		{ "Musclewalk_Csaw", "MUSCULAR", "Musclewalk_Csaw" },
		{ "Musclewalk_rocket", "MUSCULAR", "Musclewalk_rocket" },
	},

	["NEVADA"] = {
		{ "NEVADA_getin", "NEVADA", "NEVADA_getin" },
		{ "NEVADA_getout", "NEVADA", "NEVADA_getout" },
	},

	["ON_LOOKERS"] = {
		{ "lkaround_in", "ON_LOOKERS", "lkaround_in" },
		{ "lkaround_loop", "ON_LOOKERS", "lkaround_loop" },
		{ "lkaround_out", "ON_LOOKERS", "lkaround_out" },
		{ "lkup_in", "ON_LOOKERS", "lkup_in" },
		{ "lkup_loop", "ON_LOOKERS", "lkup_loop" },
		{ "lkup_out", "ON_LOOKERS", "lkup_out" },
		{ "lkup_point", "ON_LOOKERS", "lkup_point" },
		{ "panic_cower", "ON_LOOKERS", "panic_cower" },
		{ "panic_hide", "ON_LOOKERS", "panic_hide" },
		{ "panic_in", "ON_LOOKERS", "panic_in" },
		{ "panic_loop", "ON_LOOKERS", "panic_loop" },
		{ "panic_out", "ON_LOOKERS", "panic_out" },
		{ "panic_point", "ON_LOOKERS", "panic_point" },
		{ "panic_shout", "ON_LOOKERS", "panic_shout" },
		{ "Pointup_in", "ON_LOOKERS", "Pointup_in" },
		{ "Pointup_loop", "ON_LOOKERS", "Pointup_loop" },
		{ "Pointup_out", "ON_LOOKERS", "Pointup_out" },
		{ "Pointup_shout", "ON_LOOKERS", "Pointup_shout" },
		{ "point_in", "ON_LOOKERS", "point_in" },
		{ "point_loop", "ON_LOOKERS", "point_loop" },
		{ "point_out", "ON_LOOKERS", "point_out" },
		{ "shout_01", "ON_LOOKERS", "shout_01" },
		{ "shout_02", "ON_LOOKERS", "shout_02" },
		{ "shout_in", "ON_LOOKERS", "shout_in" },
		{ "shout_loop", "ON_LOOKERS", "shout_loop" },
		{ "shout_out", "ON_LOOKERS", "shout_out" },
		{ "wave_in", "ON_LOOKERS", "wave_in" },
		{ "wave_loop", "ON_LOOKERS", "wave_loop" },
		{ "wave_out", "ON_LOOKERS", "wave_out" },
	},

	["OTB"] = {
		{ "betslp_in", "OTB", "betslp_in" },
		{ "betslp_lkabt", "OTB", "betslp_lkabt" },
		{ "betslp_loop", "OTB", "betslp_loop" },
		{ "betslp_out", "OTB", "betslp_out" },
		{ "betslp_tnk", "OTB", "betslp_tnk" },
		{ "wtchrace_cmon", "OTB", "wtchrace_cmon" },
		{ "wtchrace_in", "OTB", "wtchrace_in" },
		{ "wtchrace_loop", "OTB", "wtchrace_loop" },
		{ "wtchrace_lose", "OTB", "wtchrace_lose" },
		{ "wtchrace_out", "OTB", "wtchrace_out" },
		{ "wtchrace_win", "OTB", "wtchrace_win" },
	},

	["PARACHUTE"] = {
		{ "FALL_skyDive", "PARACHUTE", "FALL_skyDive" },
		{ "FALL_SkyDive_Accel", "PARACHUTE", "FALL_SkyDive_Accel" },
		{ "FALL_skyDive_DIE", "PARACHUTE", "FALL_skyDive_DIE" },
		{ "FALL_SkyDive_L", "PARACHUTE", "FALL_SkyDive_L" },
		{ "FALL_SkyDive_R", "PARACHUTE", "FALL_SkyDive_R" },
		{ "PARA_decel", "PARACHUTE", "PARA_decel" },
		{ "PARA_decel_O", "PARACHUTE", "PARA_decel_O" },
		{ "PARA_float", "PARACHUTE", "PARA_float" },
		{ "PARA_float_O", "PARACHUTE", "PARA_float_O" },
		{ "PARA_Land", "PARACHUTE", "PARA_Land" },
		{ "PARA_Land_O", "PARACHUTE", "PARA_Land_O" },
		{ "PARA_Land_Water", "PARACHUTE", "PARA_Land_Water" },
		{ "PARA_Land_Water_O", "PARACHUTE", "PARA_Land_Water_O" },
		{ "PARA_open", "PARACHUTE", "PARA_open" },
		{ "PARA_open_O", "PARACHUTE", "PARA_open_O" },
		{ "PARA_Rip_Land_O", "PARACHUTE", "PARA_Rip_Land_O" },
		{ "PARA_Rip_Loop_O", "PARACHUTE", "PARA_Rip_Loop_O" },
		{ "PARA_Rip_O", "PARACHUTE", "PARA_Rip_O" },
		{ "PARA_steerL", "PARACHUTE", "PARA_steerL" },
		{ "PARA_steerL_O", "PARACHUTE", "PARA_steerL_O" },
		{ "PARA_steerR", "PARACHUTE", "PARA_steerR" },
		{ "PARA_steerR_O", "PARACHUTE", "PARA_steerR_O" },
	},

	["PARK"] = {
		{ "Tai_Chi_in", "PARK", "Tai_Chi_in" },
		{ "Tai_Chi_Loop", "PARK", "Tai_Chi_Loop" },
		{ "Tai_Chi_Out", "PARK", "Tai_Chi_Out" },
	},

	["PAULNMAC"] = {
		{ "Piss_in", "PAULNMAC", "Piss_in" },
		{ "Piss_loop", "PAULNMAC", "Piss_loop" },
		{ "Piss_out", "PAULNMAC", "Piss_out" },
		{ "PnM_Argue1_A", "PAULNMAC", "PnM_Argue1_A" },
		{ "PnM_Argue1_B", "PAULNMAC", "PnM_Argue1_B" },
		{ "PnM_Argue2_A", "PAULNMAC", "PnM_Argue2_A" },
		{ "PnM_Argue2_B", "PAULNMAC", "PnM_Argue2_B" },
		{ "PnM_Loop_A", "PAULNMAC", "PnM_Loop_A" },
		{ "PnM_Loop_B", "PAULNMAC", "PnM_Loop_B" },
		{ "wank_in", "PAULNMAC", "wank_in" },
		{ "wank_loop", "PAULNMAC", "wank_loop" },
		{ "wank_out", "PAULNMAC", "wank_out" },
	},

	["ped"] = {
		{ "abseil", "ped", "abseil" },
		{ "ARRESTgun", "ped", "ARRESTgun" },
		{ "ATM", "ped", "ATM" },
		{ "BIKE_elbowL", "ped", "BIKE_elbowL" },
		{ "BIKE_elbowR", "ped", "BIKE_elbowR" },
		{ "BIKE_fallR", "ped", "BIKE_fallR" },
		{ "BIKE_fall_off", "ped", "BIKE_fall_off" },
		{ "BIKE_pickupL", "ped", "BIKE_pickupL" },
		{ "BIKE_pickupR", "ped", "BIKE_pickupR" },
		{ "BIKE_pullupL", "ped", "BIKE_pullupL" },
		{ "BIKE_pullupR", "ped", "BIKE_pullupR" },
		{ "bomber", "ped", "bomber" },
		{ "CAR_alignHI_LHS", "ped", "CAR_alignHI_LHS" },
		{ "CAR_alignHI_RHS", "ped", "CAR_alignHI_RHS" },
		{ "CAR_align_LHS", "ped", "CAR_align_LHS" },
		{ "CAR_align_RHS", "ped", "CAR_align_RHS" },
		{ "CAR_closedoorL_LHS", "ped", "CAR_closedoorL_LHS" },
		{ "CAR_closedoorL_RHS", "ped", "CAR_closedoorL_RHS" },
		{ "CAR_closedoor_LHS", "ped", "CAR_closedoor_LHS" },
		{ "CAR_closedoor_RHS", "ped", "CAR_closedoor_RHS" },
		{ "CAR_close_LHS", "ped", "CAR_close_LHS" },
		{ "CAR_close_RHS", "ped", "CAR_close_RHS" },
		{ "CAR_crawloutRHS", "ped", "CAR_crawloutRHS" },
		{ "CAR_dead_LHS", "ped", "CAR_dead_LHS" },
		{ "CAR_dead_RHS", "ped", "CAR_dead_RHS" },
		{ "CAR_doorlocked_LHS", "ped", "CAR_doorlocked_LHS" },
		{ "CAR_doorlocked_RHS", "ped", "CAR_doorlocked_RHS" },
		{ "CAR_fallout_LHS", "ped", "CAR_fallout_LHS" },
		{ "CAR_fallout_RHS", "ped", "CAR_fallout_RHS" },
		{ "CAR_getinL_LHS", "ped", "CAR_getinL_LHS" },
		{ "CAR_getinL_RHS", "ped", "CAR_getinL_RHS" },
		{ "CAR_getin_LHS", "ped", "CAR_getin_LHS" },
		{ "CAR_getin_RHS", "ped", "CAR_getin_RHS" },
		{ "CAR_getoutL_LHS", "ped", "CAR_getoutL_LHS" },
		{ "CAR_getoutL_RHS", "ped", "CAR_getoutL_RHS" },
		{ "CAR_getout_LHS", "ped", "CAR_getout_LHS" },
		{ "CAR_getout_RHS", "ped", "CAR_getout_RHS" },
		{ "car_hookertalk", "ped", "car_hookertalk" },
		{ "CAR_jackedLHS", "ped", "CAR_jackedLHS" },
		{ "CAR_jackedRHS", "ped", "CAR_jackedRHS" },
		{ "CAR_jumpin_LHS", "ped", "CAR_jumpin_LHS" },
		{ "CAR_LB", "ped", "CAR_LB" },
		{ "CAR_LB_pro", "ped", "CAR_LB_pro" },
		{ "CAR_LB_weak", "ped", "CAR_LB_weak" },
		{ "CAR_LjackedLHS", "ped", "CAR_LjackedLHS" },
		{ "CAR_LjackedRHS", "ped", "CAR_LjackedRHS" },
		{ "CAR_Lshuffle_RHS", "ped", "CAR_Lshuffle_RHS" },
		{ "CAR_Lsit", "ped", "CAR_Lsit" },
		{ "CAR_open_LHS", "ped", "CAR_open_LHS" },
		{ "CAR_open_RHS", "ped", "CAR_open_RHS" },
		{ "CAR_pulloutL_LHS", "ped", "CAR_pulloutL_LHS" },
		{ "CAR_pulloutL_RHS", "ped", "CAR_pulloutL_RHS" },
		{ "CAR_pullout_LHS", "ped", "CAR_pullout_LHS" },
		{ "CAR_pullout_RHS", "ped", "CAR_pullout_RHS" },
		{ "CAR_Qjacked", "ped", "CAR_Qjacked" },
		{ "CAR_rolldoor", "ped", "CAR_rolldoor" },
		{ "CAR_rolldoorLO", "ped", "CAR_rolldoorLO" },
		{ "CAR_rollout_LHS", "ped", "CAR_rollout_LHS" },
		{ "CAR_rollout_RHS", "ped", "CAR_rollout_RHS" },
		{ "CAR_shuffle_RHS", "ped", "CAR_shuffle_RHS" },
		{ "CAR_sit", "ped", "CAR_sit" },
		{ "CAR_sitp", "ped", "CAR_sitp" },
		{ "CAR_sitpLO", "ped", "CAR_sitpLO" },
		{ "CAR_sit_pro", "ped", "CAR_sit_pro" },
		{ "CAR_sit_weak", "ped", "CAR_sit_weak" },
		{ "CAR_tune_radio", "ped", "CAR_tune_radio" },
		{ "CLIMB_idle", "ped", "CLIMB_idle" },
		{ "CLIMB_jump", "ped", "CLIMB_jump" },
		{ "CLIMB_jump2fall", "ped", "CLIMB_jump2fall" },
		{ "CLIMB_jump_B", "ped", "CLIMB_jump_B" },
		{ "CLIMB_Pull", "ped", "CLIMB_Pull" },
		{ "CLIMB_Stand", "ped", "CLIMB_Stand" },
		{ "CLIMB_Stand_finish", "ped", "CLIMB_Stand_finish" },
		{ "cower", "ped", "cower" },
		{ "Crouch_Roll_L", "ped", "Crouch_Roll_L" },
		{ "Crouch_Roll_R", "ped", "Crouch_Roll_R" },
		{ "DAM_armL_frmBK", "ped", "DAM_armL_frmBK" },
		{ "DAM_armL_frmFT", "ped", "DAM_armL_frmFT" },
		{ "DAM_armL_frmLT", "ped", "DAM_armL_frmLT" },
		{ "DAM_armR_frmBK", "ped", "DAM_armR_frmBK" },
		{ "DAM_armR_frmFT", "ped", "DAM_armR_frmFT" },
		{ "DAM_armR_frmRT", "ped", "DAM_armR_frmRT" },
		{ "DAM_LegL_frmBK", "ped", "DAM_LegL_frmBK" },
		{ "DAM_LegL_frmFT", "ped", "DAM_LegL_frmFT" },
		{ "DAM_LegL_frmLT", "ped", "DAM_LegL_frmLT" },
		{ "DAM_LegR_frmBK", "ped", "DAM_LegR_frmBK" },
		{ "DAM_LegR_frmFT", "ped", "DAM_LegR_frmFT" },
		{ "DAM_LegR_frmRT", "ped", "DAM_LegR_frmRT" },
		{ "DAM_stomach_frmBK", "ped", "DAM_stomach_frmBK" },
		{ "DAM_stomach_frmFT", "ped", "DAM_stomach_frmFT" },
		{ "DAM_stomach_frmLT", "ped", "DAM_stomach_frmLT" },
		{ "DAM_stomach_frmRT", "ped", "DAM_stomach_frmRT" },
		{ "DOOR_LHinge_O", "ped", "DOOR_LHinge_O" },
		{ "DOOR_RHinge_O", "ped", "DOOR_RHinge_O" },
		{ "DrivebyL_L", "ped", "DrivebyL_L" },
		{ "DrivebyL_R", "ped", "DrivebyL_R" },
		{ "Driveby_L", "ped", "Driveby_L" },
		{ "Driveby_R", "ped", "Driveby_R" },
		{ "DRIVE_BOAT", "ped", "DRIVE_BOAT" },
		{ "DRIVE_BOAT_back", "ped", "DRIVE_BOAT_back" },
		{ "DRIVE_BOAT_L", "ped", "DRIVE_BOAT_L" },
		{ "DRIVE_BOAT_R", "ped", "DRIVE_BOAT_R" },
		{ "Drive_L", "ped", "Drive_L" },
		{ "Drive_LO_l", "ped", "Drive_LO_l" },
		{ "Drive_LO_R", "ped", "Drive_LO_R" },
		{ "Drive_L_pro", "ped", "Drive_L_pro" },
		{ "Drive_L_pro_slow", "ped", "Drive_L_pro_slow" },
		{ "Drive_L_slow", "ped", "Drive_L_slow" },
		{ "Drive_L_weak", "ped", "Drive_L_weak" },
		{ "Drive_L_weak_slow", "ped", "Drive_L_weak_slow" },
		{ "Drive_R", "ped", "Drive_R" },
		{ "Drive_R_pro", "ped", "Drive_R_pro" },
		{ "Drive_R_pro_slow", "ped", "Drive_R_pro_slow" },
		{ "Drive_R_slow", "ped", "Drive_R_slow" },
		{ "Drive_R_weak", "ped", "Drive_R_weak" },
		{ "Drive_R_weak_slow", "ped", "Drive_R_weak_slow" },
		{ "Drive_truck", "ped", "Drive_truck" },
		{ "DRIVE_truck_back", "ped", "DRIVE_truck_back" },
		{ "DRIVE_truck_L", "ped", "DRIVE_truck_L" },
		{ "DRIVE_truck_R", "ped", "DRIVE_truck_R" },
		{ "Drown", "ped", "Drown" },
		{ "DUCK_cower", "ped", "DUCK_cower" },
		{ "endchat_01", "ped", "endchat_01" },
		{ "endchat_02", "ped", "endchat_02" },
		{ "endchat_03", "ped", "endchat_03" },
		{ "EV_dive", "ped", "EV_dive" },
		{ "EV_step", "ped", "EV_step" },
		{ "facanger", "ped", "facanger" },
		{ "facgum", "ped", "facgum" },
		{ "facsurp", "ped", "facsurp" },
		{ "facsurpm", "ped", "facsurpm" },
		{ "factalk", "ped", "factalk" },
		{ "facurios", "ped", "facurios" },
		{ "FALL_back", "ped", "FALL_back" },
		{ "FALL_collapse", "ped", "FALL_collapse" },
		{ "FALL_fall", "ped", "FALL_fall" },
		{ "FALL_front", "ped", "FALL_front" },
		{ "FALL_glide", "ped", "FALL_glide" },
		{ "FALL_land", "ped", "FALL_land" },
		{ "FALL_skyDive", "ped", "FALL_skyDive" },
		{ "Fight2Idle", "ped", "Fight2Idle" },
		{ "FightA_1", "ped", "FightA_1" },
		{ "FightA_2", "ped", "FightA_2" },
		{ "FightA_3", "ped", "FightA_3" },
		{ "FightA_block", "ped", "FightA_block" },
		{ "FightA_G", "ped", "FightA_G" },
		{ "FightA_M", "ped", "FightA_M" },
		{ "FIGHTIDLE", "ped", "FIGHTIDLE" },
		{ "FightShB", "ped", "FightShB" },
		{ "FightShF", "ped", "FightShF" },
		{ "FightSh_BWD", "ped", "FightSh_BWD" },
		{ "FightSh_FWD", "ped", "FightSh_FWD" },
		{ "FightSh_Left", "ped", "FightSh_Left" },
		{ "FightSh_Right", "ped", "FightSh_Right" },
		{ "flee_lkaround_01", "ped", "flee_lkaround_01" },
		{ "FLOOR_hit", "ped", "FLOOR_hit" },
		{ "FLOOR_hit_f", "ped", "FLOOR_hit_f" },
		{ "fucku", "ped", "fucku" },
		{ "gang_gunstand", "ped", "gang_gunstand" },
		{ "gas_cwr", "ped", "gas_cwr" },
		{ "getup", "ped", "getup" },
		{ "getup_front", "ped", "getup_front" },
		{ "gum_eat", "ped", "gum_eat" },
		{ "GunCrouchBwd", "ped", "GunCrouchBwd" },
		{ "GunCrouchFwd", "ped", "GunCrouchFwd" },
		{ "GunMove_BWD", "ped", "GunMove_BWD" },
		{ "GunMove_FWD", "ped", "GunMove_FWD" },
		{ "GunMove_L", "ped", "GunMove_L" },
		{ "GunMove_R", "ped", "GunMove_R" },
		{ "Gun_2_IDLE", "ped", "Gun_2_IDLE" },
		{ "GUN_BUTT", "ped", "GUN_BUTT" },
		{ "GUN_BUTT_crouch", "ped", "GUN_BUTT_crouch" },
		{ "Gun_stand", "ped", "Gun_stand" },
		{ "handscower", "ped", "handscower" },
		{ "handsup", "ped", "handsup" },
		{ "HitA_1", "ped", "HitA_1" },
		{ "HitA_2", "ped", "HitA_2" },
		{ "HitA_3", "ped", "HitA_3" },
		{ "HIT_back", "ped", "HIT_back" },
		{ "HIT_behind", "ped", "HIT_behind" },
		{ "HIT_front", "ped", "HIT_front" },
		{ "HIT_GUN_BUTT", "ped", "HIT_GUN_BUTT" },
		{ "HIT_L", "ped", "HIT_L" },
		{ "HIT_R", "ped", "HIT_R" },
		{ "HIT_walk", "ped", "HIT_walk" },
		{ "HIT_wall", "ped", "HIT_wall" },
		{ "Idlestance_fat", "ped", "Idlestance_fat" },
		{ "idlestance_old", "ped", "idlestance_old" },
		{ "IDLE_armed", "ped", "IDLE_armed" },
		{ "IDLE_chat", "ped", "IDLE_chat" },
		{ "IDLE_csaw", "ped", "IDLE_csaw" },
		{ "Idle_Gang1", "ped", "Idle_Gang1" },
		{ "IDLE_HBHB", "ped", "IDLE_HBHB" },
		{ "IDLE_ROCKET", "ped", "IDLE_ROCKET" },
		{ "IDLE_stance", "ped", "IDLE_stance" },
		{ "IDLE_taxi", "ped", "IDLE_taxi" },
		{ "IDLE_tired", "ped", "IDLE_tired" },
		{ "Jetpack_Idle", "ped", "Jetpack_Idle" },
		{ "JOG_femaleA", "ped", "JOG_femaleA" },
		{ "JOG_maleA", "ped", "JOG_maleA" },
		{ "JUMP_glide", "ped", "JUMP_glide" },
		{ "JUMP_land", "ped", "JUMP_land" },
		{ "JUMP_launch", "ped", "JUMP_launch" },
		{ "JUMP_launch_R", "ped", "JUMP_launch_R" },
		{ "KART_drive", "ped", "KART_drive" },
		{ "KART_L", "ped", "KART_L" },
		{ "KART_LB", "ped", "KART_LB" },
		{ "KART_R", "ped", "KART_R" },
		{ "KD_left", "ped", "KD_left" },
		{ "KD_right", "ped", "KD_right" },
		{ "KO_shot_face", "ped", "KO_shot_face" },
		{ "KO_shot_front", "ped", "KO_shot_front" },
		{ "KO_shot_stom", "ped", "KO_shot_stom" },
		{ "KO_skid_back", "ped", "KO_skid_back" },
		{ "KO_skid_front", "ped", "KO_skid_front" },
		{ "KO_spin_L", "ped", "KO_spin_L" },
		{ "KO_spin_R", "ped", "KO_spin_R" },
		{ "pass_Smoke_in_car", "ped", "pass_Smoke_in_car" },
		{ "phone_in", "ped", "phone_in" },
		{ "phone_out", "ped", "phone_out" },
		{ "phone_talk", "ped", "phone_talk" },
		{ "Player_Sneak", "ped", "Player_Sneak" },
		{ "Player_Sneak_walkstart", "ped", "Player_Sneak_walkstart" },
		{ "roadcross", "ped", "roadcross" },
		{ "roadcross_female", "ped", "roadcross_female" },
		{ "roadcross_gang", "ped", "roadcross_gang" },
		{ "roadcross_old", "ped", "roadcross_old" },
		{ "run_1armed", "ped", "run_1armed" },
		{ "run_armed", "ped", "run_armed" },
		{ "run_civi", "ped", "run_civi" },
		{ "run_csaw", "ped", "run_csaw" },
		{ "run_fat", "ped", "run_fat" },
		{ "run_fatold", "ped", "run_fatold" },
		{ "run_gang1", "ped", "run_gang1" },
		{ "run_left", "ped", "run_left" },
		{ "run_old", "ped", "run_old" },
		{ "run_player", "ped", "run_player" },
		{ "run_right", "ped", "run_right" },
		{ "run_rocket", "ped", "run_rocket" },
		{ "Run_stop", "ped", "Run_stop" },
		{ "Run_stopR", "ped", "Run_stopR" },
		{ "Run_Wuzi", "ped", "Run_Wuzi" },
		{ "SEAT_down", "ped", "SEAT_down" },
		{ "SEAT_idle", "ped", "SEAT_idle" },
		{ "SEAT_up", "ped", "SEAT_up" },
		{ "SHOT_leftP", "ped", "SHOT_leftP" },
		{ "SHOT_partial", "ped", "SHOT_partial" },
		{ "SHOT_partial_B", "ped", "SHOT_partial_B" },
		{ "SHOT_rightP", "ped", "SHOT_rightP" },
		{ "Shove_Partial", "ped", "Shove_Partial" },
		{ "Smoke_in_car", "ped", "Smoke_in_car" },
		{ "sprint_civi", "ped", "sprint_civi" },
		{ "sprint_panic", "ped", "sprint_panic" },
		{ "Sprint_Wuzi", "ped", "Sprint_Wuzi" },
		{ "swat_run", "ped", "swat_run" },
		{ "Swim_Tread", "ped", "Swim_Tread" },
		{ "Tap_hand", "ped", "Tap_hand" },
		{ "Tap_handP", "ped", "Tap_handP" },
		{ "turn_180", "ped", "turn_180" },
		{ "Turn_L", "ped", "Turn_L" },
		{ "Turn_R", "ped", "Turn_R" },
		{ "WALK_armed", "ped", "WALK_armed" },
		{ "WALK_civi", "ped", "WALK_civi" },
		{ "WALK_csaw", "ped", "WALK_csaw" },
		{ "Walk_DoorPartial", "ped", "Walk_DoorPartial" },
		{ "WALK_drunk", "ped", "WALK_drunk" },
		{ "WALK_fat", "ped", "WALK_fat" },
		{ "WALK_fatold", "ped", "WALK_fatold" },
		{ "WALK_gang1", "ped", "WALK_gang1" },
		{ "WALK_gang2", "ped", "WALK_gang2" },
		{ "WALK_old", "ped", "WALK_old" },
		{ "WALK_player", "ped", "WALK_player" },
		{ "WALK_rocket", "ped", "WALK_rocket" },
		{ "WALK_shuffle", "ped", "WALK_shuffle" },
		{ "WALK_start", "ped", "WALK_start" },
		{ "WALK_start_armed", "ped", "WALK_start_armed" },
		{ "WALK_start_csaw", "ped", "WALK_start_csaw" },
		{ "WALK_start_rocket", "ped", "WALK_start_rocket" },
		{ "Walk_Wuzi", "ped", "Walk_Wuzi" },
		{ "WEAPON_crouch", "ped", "WEAPON_crouch" },
		{ "woman_idlestance", "ped", "woman_idlestance" },
		{ "woman_run", "ped", "woman_run" },
		{ "WOMAN_runbusy", "ped", "WOMAN_runbusy" },
		{ "WOMAN_runfatold", "ped", "WOMAN_runfatold" },
		{ "woman_runpanic", "ped", "woman_runpanic" },
		{ "WOMAN_runsexy", "ped", "WOMAN_runsexy" },
		{ "WOMAN_walkbusy", "ped", "WOMAN_walkbusy" },
		{ "WOMAN_walkfatold", "ped", "WOMAN_walkfatold" },
		{ "WOMAN_walknorm", "ped", "WOMAN_walknorm" },
		{ "WOMAN_walkold", "ped", "WOMAN_walkold" },
		{ "WOMAN_walkpro", "ped", "WOMAN_walkpro" },
		{ "WOMAN_walksexy", "ped", "WOMAN_walksexy" },
		{ "WOMAN_walkshop", "ped", "WOMAN_walkshop" },
		{ "XPRESSscratch", "ped", "XPRESSscratch" },
	},

	["PLAYER_DVBYS"] = {
		{ "Plyr_DrivebyBwd", "PLAYER_DVBYS", "Plyr_DrivebyBwd" },
		{ "Plyr_DrivebyFwd", "PLAYER_DVBYS", "Plyr_DrivebyFwd" },
		{ "Plyr_DrivebyLHS", "PLAYER_DVBYS", "Plyr_DrivebyLHS" },
		{ "Plyr_DrivebyRHS", "PLAYER_DVBYS", "Plyr_DrivebyRHS" },
	},

	["PLAYIDLES"] = {
		{ "shift", "PLAYIDLES", "shift" },
		{ "shldr", "PLAYIDLES", "shldr" },
		{ "stretch", "PLAYIDLES", "stretch" },
		{ "strleg", "PLAYIDLES", "strleg" },
		{ "time", "PLAYIDLES", "time" },
	},

	["POLICE"] = {
		{ "CopTraf_Away", "POLICE", "CopTraf_Away" },
		{ "CopTraf_Come", "POLICE", "CopTraf_Come" },
		{ "CopTraf_Left", "POLICE", "CopTraf_Left" },
		{ "CopTraf_Stop", "POLICE", "CopTraf_Stop" },
		{ "COP_getoutcar_LHS", "POLICE", "COP_getoutcar_LHS" },
		{ "Cop_move_FWD", "POLICE", "Cop_move_FWD" },
		{ "crm_drgbst_01", "POLICE", "crm_drgbst_01" },
		{ "Door_Kick", "POLICE", "Door_Kick" },
		{ "plc_drgbst_01", "POLICE", "plc_drgbst_01" },
		{ "plc_drgbst_02", "POLICE", "plc_drgbst_02" },
	},

	["POOL"] = {
		{ "POOL_ChalkCue", "POOL", "POOL_ChalkCue" },
		{ "POOL_Idle_Stance", "POOL", "POOL_Idle_Stance" },
		{ "POOL_Long_Shot", "POOL", "POOL_Long_Shot" },
		{ "POOL_Long_Shot_O", "POOL", "POOL_Long_Shot_O" },
		{ "POOL_Long_Start", "POOL", "POOL_Long_Start" },
		{ "POOL_Long_Start_O", "POOL", "POOL_Long_Start_O" },
		{ "POOL_Med_Shot", "POOL", "POOL_Med_Shot" },
		{ "POOL_Med_Shot_O", "POOL", "POOL_Med_Shot_O" },
		{ "POOL_Med_Start", "POOL", "POOL_Med_Start" },
		{ "POOL_Med_Start_O", "POOL", "POOL_Med_Start_O" },
		{ "POOL_Place_White", "POOL", "POOL_Place_White" },
		{ "POOL_Short_Shot", "POOL", "POOL_Short_Shot" },
		{ "POOL_Short_Shot_O", "POOL", "POOL_Short_Shot_O" },
		{ "POOL_Short_Start", "POOL", "POOL_Short_Start" },
		{ "POOL_Short_Start_O", "POOL", "POOL_Short_Start_O" },
		{ "POOL_Walk", "POOL", "POOL_Walk" },
		{ "POOL_Walk_Start", "POOL", "POOL_Walk_Start" },
		{ "POOL_XLong_Shot", "POOL", "POOL_XLong_Shot" },
		{ "POOL_XLong_Shot_O", "POOL", "POOL_XLong_Shot_O" },
		{ "POOL_XLong_Start", "POOL", "POOL_XLong_Start" },
		{ "POOL_XLong_Start_O", "POOL", "POOL_XLong_Start_O" },
	},

	["POOR"] = {
		{ "WINWASH_Start", "POOR", "WINWASH_Start" },
		{ "WINWASH_Wash2Beg", "POOR", "WINWASH_Wash2Beg" },
	},

	["PYTHON"] = {
		{ "python_crouchfire", "PYTHON", "python_crouchfire" },
		{ "python_crouchreload", "PYTHON", "python_crouchreload" },
		{ "python_fire", "PYTHON", "python_fire" },
		{ "python_fire_poor", "PYTHON", "python_fire_poor" },
		{ "python_reload", "PYTHON", "python_reload" },
	},

	["QUAD"] = {
		{ "QUAD_back", "QUAD", "QUAD_back" },
		{ "QUAD_driveby_FT", "QUAD", "QUAD_driveby_FT" },
		{ "QUAD_driveby_LHS", "QUAD", "QUAD_driveby_LHS" },
		{ "QUAD_driveby_RHS", "QUAD", "QUAD_driveby_RHS" },
		{ "QUAD_FWD", "QUAD", "QUAD_FWD" },
		{ "QUAD_getoff_B", "QUAD", "QUAD_getoff_B" },
		{ "QUAD_getoff_LHS", "QUAD", "QUAD_getoff_LHS" },
		{ "QUAD_getoff_RHS", "QUAD", "QUAD_getoff_RHS" },
		{ "QUAD_geton_LHS", "QUAD", "QUAD_geton_LHS" },
		{ "QUAD_geton_RHS", "QUAD", "QUAD_geton_RHS" },
		{ "QUAD_hit", "QUAD", "QUAD_hit" },
		{ "QUAD_kick", "QUAD", "QUAD_kick" },
		{ "QUAD_Left", "QUAD", "QUAD_Left" },
		{ "QUAD_passenger", "QUAD", "QUAD_passenger" },
		{ "QUAD_reverse", "QUAD", "QUAD_reverse" },
		{ "QUAD_ride", "QUAD", "QUAD_ride" },
		{ "QUAD_Right", "QUAD", "QUAD_Right" },
	},

	["QUAD_DBZ"] = {
		{ "Pass_Driveby_BWD", "QUAD_DBZ", "Pass_Driveby_BWD" },
		{ "Pass_Driveby_FWD", "QUAD_DBZ", "Pass_Driveby_FWD" },
		{ "Pass_Driveby_LHS", "QUAD_DBZ", "Pass_Driveby_LHS" },
		{ "Pass_Driveby_RHS", "QUAD_DBZ", "Pass_Driveby_RHS" },
	},

	["RAPPING"] = {
		{ "Laugh_01", "RAPPING", "Laugh_01" },
		{ "RAP_A_IN", "RAPPING", "RAP_A_IN" },
		{ "RAP_A_Loop", "RAPPING", "RAP_A_Loop" },
		{ "RAP_A_OUT", "RAPPING", "RAP_A_OUT" },
		{ "RAP_B_IN", "RAPPING", "RAP_B_IN" },
		{ "RAP_B_Loop", "RAPPING", "RAP_B_Loop" },
		{ "RAP_B_OUT", "RAPPING", "RAP_B_OUT" },
		{ "RAP_C_Loop", "RAPPING", "RAP_C_Loop" },
	},

	["RIFLE"] = {
		{ "RIFLE_crouchfire", "RIFLE", "RIFLE_crouchfire" },
		{ "RIFLE_crouchload", "RIFLE", "RIFLE_crouchload" },
		{ "RIFLE_fire", "RIFLE", "RIFLE_fire" },
		{ "RIFLE_fire_poor", "RIFLE", "RIFLE_fire_poor" },
		{ "RIFLE_load", "RIFLE", "RIFLE_load" },
	},

	["RIOT"] = {
		{ "RIOT_ANGRY", "RIOT", "RIOT_ANGRY" },
		{ "RIOT_ANGRY_B", "RIOT", "RIOT_ANGRY_B" },
		{ "RIOT_challenge", "RIOT", "RIOT_challenge" },
		{ "RIOT_CHANT", "RIOT", "RIOT_CHANT" },
		{ "RIOT_FUKU", "RIOT", "RIOT_FUKU" },
		{ "RIOT_PUNCHES", "RIOT", "RIOT_PUNCHES" },
		{ "RIOT_shout", "RIOT", "RIOT_shout" },
	},

	["ROB_BANK"] = {
		{ "CAT_Safe_End", "ROB_BANK", "CAT_Safe_End" },
		{ "CAT_Safe_Open", "ROB_BANK", "CAT_Safe_Open" },
		{ "CAT_Safe_Open_O", "ROB_BANK", "CAT_Safe_Open_O" },
		{ "CAT_Safe_Rob", "ROB_BANK", "CAT_Safe_Rob" },
		{ "SHP_HandsUp_Scr", "ROB_BANK", "SHP_HandsUp_Scr" },
	},

	["ROCKET"] = {
		{ "idle_rocket", "ROCKET", "idle_rocket" },
		{ "RocketFire", "ROCKET", "RocketFire" },
		{ "run_rocket", "ROCKET", "run_rocket" },
		{ "walk_rocket", "ROCKET", "walk_rocket" },
		{ "WALK_start_rocket", "ROCKET", "WALK_start_rocket" },
	},

	["RUSTLER"] = {
		{ "Plane_align_LHS", "RUSTLER", "Plane_align_LHS" },
		{ "Plane_close", "RUSTLER", "Plane_close" },
		{ "Plane_getin", "RUSTLER", "Plane_getin" },
		{ "Plane_getout", "RUSTLER", "Plane_getout" },
		{ "Plane_open", "RUSTLER", "Plane_open" },
	},

	["RYDER"] = {
		{ "RYD_Beckon_01", "RYDER", "RYD_Beckon_01" },
		{ "RYD_Beckon_02", "RYDER", "RYD_Beckon_02" },
		{ "RYD_Beckon_03", "RYDER", "RYD_Beckon_03" },
		{ "RYD_Die_PT1", "RYDER", "RYD_Die_PT1" },
		{ "RYD_Die_PT2", "RYDER", "RYD_Die_PT2" },
		{ "Van_Crate_L", "RYDER", "Van_Crate_L" },
		{ "Van_Crate_R", "RYDER", "Van_Crate_R" },
		{ "Van_Fall_L", "RYDER", "Van_Fall_L" },
		{ "Van_Fall_R", "RYDER", "Van_Fall_R" },
		{ "Van_Lean_L", "RYDER", "Van_Lean_L" },
		{ "Van_Lean_R", "RYDER", "Van_Lean_R" },
		{ "VAN_PickUp_E", "RYDER", "VAN_PickUp_E" },
		{ "VAN_PickUp_S", "RYDER", "VAN_PickUp_S" },
		{ "Van_Stand", "RYDER", "Van_Stand" },
		{ "Van_Stand_Crate", "RYDER", "Van_Stand_Crate" },
		{ "Van_Throw", "RYDER", "Van_Throw" },
	},

	["SCRATCHING"] = {
		{ "scdldlp", "SCRATCHING", "scdldlp" },
		{ "scdlulp", "SCRATCHING", "scdlulp" },
		{ "scdrdlp", "SCRATCHING", "scdrdlp" },
		{ "scdrulp", "SCRATCHING", "scdrulp" },
		{ "sclng_l", "SCRATCHING", "sclng_l" },
		{ "sclng_r", "SCRATCHING", "sclng_r" },
		{ "scmid_l", "SCRATCHING", "scmid_l" },
		{ "scmid_r", "SCRATCHING", "scmid_r" },
		{ "scshrtl", "SCRATCHING", "scshrtl" },
		{ "scshrtr", "SCRATCHING", "scshrtr" },
		{ "sc_ltor", "SCRATCHING", "sc_ltor" },
		{ "sc_rtol", "SCRATCHING", "sc_rtol" },
	},

	["SHAMAL"] = {
		{ "SHAMAL_align", "SHAMAL", "SHAMAL_align" },
		{ "SHAMAL_getin_LHS", "SHAMAL", "SHAMAL_getin_LHS" },
		{ "SHAMAL_getout_LHS", "SHAMAL", "SHAMAL_getout_LHS" },
		{ "SHAMAL_open", "SHAMAL", "SHAMAL_open" },
	},

	["SHOP"] = {
		{ "ROB_2Idle", "SHOP", "ROB_2Idle" },
		{ "ROB_Loop", "SHOP", "ROB_Loop" },
		{ "ROB_Loop_Threat", "SHOP", "ROB_Loop_Threat" },
		{ "ROB_Shifty", "SHOP", "ROB_Shifty" },
		{ "ROB_StickUp_In", "SHOP", "ROB_StickUp_In" },
		{ "SHP_Duck", "SHOP", "SHP_Duck" },
		{ "SHP_Duck_Aim", "SHOP", "SHP_Duck_Aim" },
		{ "SHP_Duck_Fire", "SHOP", "SHP_Duck_Fire" },
		{ "SHP_Gun_Aim", "SHOP", "SHP_Gun_Aim" },
		{ "SHP_Gun_Duck", "SHOP", "SHP_Gun_Duck" },
		{ "SHP_Gun_Fire", "SHOP", "SHP_Gun_Fire" },
		{ "SHP_Gun_Grab", "SHOP", "SHP_Gun_Grab" },
		{ "SHP_Gun_Threat", "SHOP", "SHP_Gun_Threat" },
		{ "SHP_HandsUp_Scr", "SHOP", "SHP_HandsUp_Scr" },
		{ "SHP_Jump_Glide", "SHOP", "SHP_Jump_Glide" },
		{ "SHP_Jump_Land", "SHOP", "SHP_Jump_Land" },
		{ "SHP_Jump_Launch", "SHOP", "SHP_Jump_Launch" },
		{ "SHP_Rob_GiveCash", "SHOP", "SHP_Rob_GiveCash" },
		{ "SHP_Rob_HandsUp", "SHOP", "SHP_Rob_HandsUp" },
		{ "SHP_Rob_React", "SHOP", "SHP_Rob_React" },
		{ "SHP_Serve_End", "SHOP", "SHP_Serve_End" },
		{ "SHP_Serve_Idle", "SHOP", "SHP_Serve_Idle" },
		{ "SHP_Serve_Loop", "SHOP", "SHP_Serve_Loop" },
		{ "SHP_Serve_Start", "SHOP", "SHP_Serve_Start" },
		{ "Smoke_RYD", "SHOP", "Smoke_RYD" },
	},

	["SHOTGUN"] = {
		{ "shotgun_crouchfire", "SHOTGUN", "shotgun_crouchfire" },
		{ "shotgun_fire", "SHOTGUN", "shotgun_fire" },
		{ "shotgun_fire_poor", "SHOTGUN", "shotgun_fire_poor" },
	},

	["SILENCED"] = {
		{ "CrouchReload", "SILENCED", "CrouchReload" },
		{ "SilenceCrouchfire", "SILENCED", "SilenceCrouchfire" },
		{ "Silence_fire", "SILENCED", "Silence_fire" },
		{ "Silence_reload", "SILENCED", "Silence_reload" },
	},

	["SKATE"] = {
		{ "skate_idle", "SKATE", "skate_idle" },
		{ "skate_run", "SKATE", "skate_run" },
		{ "skate_sprint", "SKATE", "skate_sprint" },
	},

	["SMOKING"] = {
		{ "F_smklean_loop", "SMOKING", "F_smklean_loop" },
		{ "M_smklean_loop", "SMOKING", "M_smklean_loop" },
		{ "M_smkstnd_loop", "SMOKING", "M_smkstnd_loop" },
		{ "M_smk_drag", "SMOKING", "M_smk_drag" },
		{ "M_smk_in", "SMOKING", "M_smk_in" },
		{ "M_smk_loop", "SMOKING", "M_smk_loop" },
		{ "M_smk_out", "SMOKING", "M_smk_out" },
		{ "M_smk_tap", "SMOKING", "M_smk_tap" },
	},

	["SNIPER"] = {
		{ "WEAPON_sniper", "SNIPER", "WEAPON_sniper" },
	},

	["SPRAYCAN"] = {
		{ "spraycan_fire", "SPRAYCAN", "spraycan_fire" },
		{ "spraycan_full", "SPRAYCAN", "spraycan_full" },
	},

	["STRIP"] = {
		{ "PLY_CASH", "STRIP", "PLY_CASH" },
		{ "PUN_CASH", "STRIP", "PUN_CASH" },
		{ "PUN_HOLLER", "STRIP", "PUN_HOLLER" },
		{ "PUN_LOOP", "STRIP", "PUN_LOOP" },
		{ "strip_A", "STRIP", "strip_A" },
		{ "strip_B", "STRIP", "strip_B" },
		{ "strip_C", "STRIP", "strip_C" },
		{ "strip_D", "STRIP", "strip_D" },
		{ "strip_E", "STRIP", "strip_E" },
		{ "strip_F", "STRIP", "strip_F" },
		{ "strip_G", "STRIP", "strip_G" },
		{ "STR_A2B", "STRIP", "STR_A2B" },
		{ "STR_B2A", "STRIP", "STR_B2A" },
		{ "STR_B2C", "STRIP", "STR_B2C" },
		{ "STR_C1", "STRIP", "STR_C1" },
		{ "STR_C2", "STRIP", "STR_C2" },
		{ "STR_C2B", "STRIP", "STR_C2B" },
		{ "STR_Loop_A", "STRIP", "STR_Loop_A" },
		{ "STR_Loop_B", "STRIP", "STR_Loop_B" },
		{ "STR_Loop_C", "STRIP", "STR_Loop_C" },
	},

	["SUNBATHE"] = {
		{ "batherdown", "SUNBATHE", "batherdown" },
		{ "batherup", "SUNBATHE", "batherup" },
		{ "Lay_Bac_in", "SUNBATHE", "Lay_Bac_in" },
		{ "Lay_Bac_out", "SUNBATHE", "Lay_Bac_out" },
		{ "ParkSit_M_IdleA", "SUNBATHE", "ParkSit_M_IdleA" },
		{ "ParkSit_M_IdleB", "SUNBATHE", "ParkSit_M_IdleB" },
		{ "ParkSit_M_IdleC", "SUNBATHE", "ParkSit_M_IdleC" },
		{ "ParkSit_M_in", "SUNBATHE", "ParkSit_M_in" },
		{ "ParkSit_M_out", "SUNBATHE", "ParkSit_M_out" },
		{ "ParkSit_W_idleA", "SUNBATHE", "ParkSit_W_idleA" },
		{ "ParkSit_W_idleB", "SUNBATHE", "ParkSit_W_idleB" },
		{ "ParkSit_W_idleC", "SUNBATHE", "ParkSit_W_idleC" },
		{ "ParkSit_W_in", "SUNBATHE", "ParkSit_W_in" },
		{ "ParkSit_W_out", "SUNBATHE", "ParkSit_W_out" },
		{ "SBATHE_F_LieB2Sit", "SUNBATHE", "SBATHE_F_LieB2Sit" },
		{ "SBATHE_F_Out", "SUNBATHE", "SBATHE_F_Out" },
		{ "SitnWait_in_W", "SUNBATHE", "SitnWait_in_W" },
		{ "SitnWait_out_W", "SUNBATHE", "SitnWait_out_W" },
	},

	["SWAT"] = {
		{ "gnstwall_injurd", "SWAT", "gnstwall_injurd" },
		{ "JMP_Wall1m_180", "SWAT", "JMP_Wall1m_180" },
		{ "Rail_fall", "SWAT", "Rail_fall" },
		{ "Rail_fall_crawl", "SWAT", "Rail_fall_crawl" },
		{ "swt_breach_01", "SWAT", "swt_breach_01" },
		{ "swt_breach_02", "SWAT", "swt_breach_02" },
		{ "swt_breach_03", "SWAT", "swt_breach_03" },
		{ "swt_go", "SWAT", "swt_go" },
		{ "swt_lkt", "SWAT", "swt_lkt" },
		{ "swt_sty", "SWAT", "swt_sty" },
		{ "swt_vent_01", "SWAT", "swt_vent_01" },
		{ "swt_vent_02", "SWAT", "swt_vent_02" },
		{ "swt_vnt_sht_die", "SWAT", "swt_vnt_sht_die" },
		{ "swt_vnt_sht_in", "SWAT", "swt_vnt_sht_in" },
		{ "swt_vnt_sht_loop", "SWAT", "swt_vnt_sht_loop" },
		{ "swt_wllpk_L", "SWAT", "swt_wllpk_L" },
		{ "swt_wllpk_L_back", "SWAT", "swt_wllpk_L_back" },
		{ "swt_wllpk_R", "SWAT", "swt_wllpk_R" },
		{ "swt_wllpk_R_back", "SWAT", "swt_wllpk_R_back" },
		{ "swt_wllshoot_in_L", "SWAT", "swt_wllshoot_in_L" },
		{ "swt_wllshoot_in_R", "SWAT", "swt_wllshoot_in_R" },
		{ "swt_wllshoot_out_L", "SWAT", "swt_wllshoot_out_L" },
		{ "swt_wllshoot_out_R", "SWAT", "swt_wllshoot_out_R" },
	},

	["SWEET"] = {
		{ "ho_ass_slapped", "SWEET", "ho_ass_slapped" },
		{ "LaFin_Player", "SWEET", "LaFin_Player" },
		{ "LaFin_Sweet", "SWEET", "LaFin_Sweet" },
		{ "plyr_hndshldr_01", "SWEET", "plyr_hndshldr_01" },
		{ "sweet_ass_slap", "SWEET", "sweet_ass_slap" },
		{ "sweet_hndshldr_01", "SWEET", "sweet_hndshldr_01" },
		{ "Sweet_injuredloop", "SWEET", "Sweet_injuredloop" },
	},

	["SWIM"] = {
		{ "Swim_Breast", "SWIM", "Swim_Breast" },
		{ "SWIM_crawl", "SWIM", "SWIM_crawl" },
		{ "Swim_Dive_Under", "SWIM", "Swim_Dive_Under" },
		{ "Swim_Glide", "SWIM", "Swim_Glide" },
		{ "Swim_jumpout", "SWIM", "Swim_jumpout" },
		{ "Swim_Tread", "SWIM", "Swim_Tread" },
		{ "Swim_Under", "SWIM", "Swim_Under" },
	},

	["SWORD"] = {
		{ "sword_1", "SWORD", "sword_1" },
		{ "sword_2", "SWORD", "sword_2" },
		{ "sword_3", "SWORD", "sword_3" },
		{ "sword_4", "SWORD", "sword_4" },
		{ "sword_block", "SWORD", "sword_block" },
		{ "Sword_Hit_1", "SWORD", "Sword_Hit_1" },
		{ "Sword_Hit_2", "SWORD", "Sword_Hit_2" },
		{ "Sword_Hit_3", "SWORD", "Sword_Hit_3" },
		{ "sword_IDLE", "SWORD", "sword_IDLE" },
		{ "sword_part", "SWORD", "sword_part" },
	},

	["TANK"] = {
		{ "TANK_align_LHS", "TANK", "TANK_align_LHS" },
		{ "TANK_close_LHS", "TANK", "TANK_close_LHS" },
		{ "TANK_doorlocked", "TANK", "TANK_doorlocked" },
		{ "TANK_getin_LHS", "TANK", "TANK_getin_LHS" },
		{ "TANK_getout_LHS", "TANK", "TANK_getout_LHS" },
		{ "TANK_open_LHS", "TANK", "TANK_open_LHS" },
	},

	["TATTOOS"] = {
		{ "TAT_ArmL_In_O", "TATTOOS", "TAT_ArmL_In_O" },
		{ "TAT_ArmL_In_P", "TATTOOS", "TAT_ArmL_In_P" },
		{ "TAT_ArmL_In_T", "TATTOOS", "TAT_ArmL_In_T" },
		{ "TAT_ArmL_Out_O", "TATTOOS", "TAT_ArmL_Out_O" },
		{ "TAT_ArmL_Out_P", "TATTOOS", "TAT_ArmL_Out_P" },
		{ "TAT_ArmL_Out_T", "TATTOOS", "TAT_ArmL_Out_T" },
		{ "TAT_ArmL_Pose_O", "TATTOOS", "TAT_ArmL_Pose_O" },
		{ "TAT_ArmL_Pose_P", "TATTOOS", "TAT_ArmL_Pose_P" },
		{ "TAT_ArmL_Pose_T", "TATTOOS", "TAT_ArmL_Pose_T" },
		{ "TAT_ArmR_In_O", "TATTOOS", "TAT_ArmR_In_O" },
		{ "TAT_ArmR_In_P", "TATTOOS", "TAT_ArmR_In_P" },
		{ "TAT_ArmR_In_T", "TATTOOS", "TAT_ArmR_In_T" },
		{ "TAT_ArmR_Out_O", "TATTOOS", "TAT_ArmR_Out_O" },
		{ "TAT_ArmR_Out_P", "TATTOOS", "TAT_ArmR_Out_P" },
		{ "TAT_ArmR_Out_T", "TATTOOS", "TAT_ArmR_Out_T" },
		{ "TAT_ArmR_Pose_O", "TATTOOS", "TAT_ArmR_Pose_O" },
		{ "TAT_ArmR_Pose_P", "TATTOOS", "TAT_ArmR_Pose_P" },
		{ "TAT_ArmR_Pose_T", "TATTOOS", "TAT_ArmR_Pose_T" },
		{ "TAT_Back_In_O", "TATTOOS", "TAT_Back_In_O" },
		{ "TAT_Back_In_P", "TATTOOS", "TAT_Back_In_P" },
		{ "TAT_Back_In_T", "TATTOOS", "TAT_Back_In_T" },
		{ "TAT_Back_Out_O", "TATTOOS", "TAT_Back_Out_O" },
		{ "TAT_Back_Out_P", "TATTOOS", "TAT_Back_Out_P" },
		{ "TAT_Back_Out_T", "TATTOOS", "TAT_Back_Out_T" },
		{ "TAT_Back_Pose_O", "TATTOOS", "TAT_Back_Pose_O" },
		{ "TAT_Back_Pose_P", "TATTOOS", "TAT_Back_Pose_P" },
		{ "TAT_Back_Pose_T", "TATTOOS", "TAT_Back_Pose_T" },
		{ "TAT_Back_Sit_In_P", "TATTOOS", "TAT_Back_Sit_In_P" },
		{ "TAT_Back_Sit_Loop_P", "TATTOOS", "TAT_Back_Sit_Loop_P" },
		{ "TAT_Back_Sit_Out_P", "TATTOOS", "TAT_Back_Sit_Out_P" },
		{ "TAT_Bel_In_O", "TATTOOS", "TAT_Bel_In_O" },
		{ "TAT_Bel_In_T", "TATTOOS", "TAT_Bel_In_T" },
		{ "TAT_Bel_Out_O", "TATTOOS", "TAT_Bel_Out_O" },
		{ "TAT_Bel_Out_T", "TATTOOS", "TAT_Bel_Out_T" },
		{ "TAT_Bel_Pose_O", "TATTOOS", "TAT_Bel_Pose_O" },
		{ "TAT_Bel_Pose_T", "TATTOOS", "TAT_Bel_Pose_T" },
		{ "TAT_Che_In_O", "TATTOOS", "TAT_Che_In_O" },
		{ "TAT_Che_In_P", "TATTOOS", "TAT_Che_In_P" },
		{ "TAT_Che_In_T", "TATTOOS", "TAT_Che_In_T" },
		{ "TAT_Che_Out_O", "TATTOOS", "TAT_Che_Out_O" },
		{ "TAT_Che_Out_P", "TATTOOS", "TAT_Che_Out_P" },
		{ "TAT_Che_Out_T", "TATTOOS", "TAT_Che_Out_T" },
		{ "TAT_Che_Pose_O", "TATTOOS", "TAT_Che_Pose_O" },
		{ "TAT_Che_Pose_P", "TATTOOS", "TAT_Che_Pose_P" },
		{ "TAT_Che_Pose_T", "TATTOOS", "TAT_Che_Pose_T" },
		{ "TAT_Drop_O", "TATTOOS", "TAT_Drop_O" },
		{ "TAT_Idle_Loop_O", "TATTOOS", "TAT_Idle_Loop_O" },
		{ "TAT_Idle_Loop_T", "TATTOOS", "TAT_Idle_Loop_T" },
		{ "TAT_Sit_In_O", "TATTOOS", "TAT_Sit_In_O" },
		{ "TAT_Sit_In_P", "TATTOOS", "TAT_Sit_In_P" },
		{ "TAT_Sit_In_T", "TATTOOS", "TAT_Sit_In_T" },
		{ "TAT_Sit_Loop_O", "TATTOOS", "TAT_Sit_Loop_O" },
		{ "TAT_Sit_Loop_P", "TATTOOS", "TAT_Sit_Loop_P" },
		{ "TAT_Sit_Loop_T", "TATTOOS", "TAT_Sit_Loop_T" },
		{ "TAT_Sit_Out_O", "TATTOOS", "TAT_Sit_Out_O" },
		{ "TAT_Sit_Out_P", "TATTOOS", "TAT_Sit_Out_P" },
		{ "TAT_Sit_Out_T", "TATTOOS", "TAT_Sit_Out_T" },
	},

	["TEC"] = {
		{ "TEC_crouchfire", "TEC", "TEC_crouchfire" },
		{ "TEC_crouchreload", "TEC", "TEC_crouchreload" },
		{ "TEC_fire", "TEC", "TEC_fire" },
		{ "TEC_reload", "TEC", "TEC_reload" },
	},

	["TRAIN"] = {
		{ "tran_gtup", "TRAIN", "tran_gtup" },
		{ "tran_hng", "TRAIN", "tran_hng" },
		{ "tran_ouch", "TRAIN", "tran_ouch" },
		{ "tran_stmb", "TRAIN", "tran_stmb" },
	},

	["TRUCK"] = {
		{ "TRUCK_ALIGN_LHS", "TRUCK", "TRUCK_ALIGN_LHS" },
		{ "TRUCK_ALIGN_RHS", "TRUCK", "TRUCK_ALIGN_RHS" },
		{ "TRUCK_closedoor_LHS", "TRUCK", "TRUCK_closedoor_LHS" },
		{ "TRUCK_closedoor_RHS", "TRUCK", "TRUCK_closedoor_RHS" },
		{ "TRUCK_close_LHS", "TRUCK", "TRUCK_close_LHS" },
		{ "TRUCK_close_RHS", "TRUCK", "TRUCK_close_RHS" },
		{ "TRUCK_getin_LHS", "TRUCK", "TRUCK_getin_LHS" },
		{ "TRUCK_getin_RHS", "TRUCK", "TRUCK_getin_RHS" },
		{ "TRUCK_getout_LHS", "TRUCK", "TRUCK_getout_LHS" },
		{ "TRUCK_getout_RHS", "TRUCK", "TRUCK_getout_RHS" },
		{ "TRUCK_jackedLHS", "TRUCK", "TRUCK_jackedLHS" },
		{ "TRUCK_jackedRHS", "TRUCK", "TRUCK_jackedRHS" },
		{ "TRUCK_open_LHS", "TRUCK", "TRUCK_open_LHS" },
		{ "TRUCK_open_RHS", "TRUCK", "TRUCK_open_RHS" },
		{ "TRUCK_pullout_LHS", "TRUCK", "TRUCK_pullout_LHS" },
		{ "TRUCK_pullout_RHS", "TRUCK", "TRUCK_pullout_RHS" },
		{ "TRUCK_Shuffle", "TRUCK", "TRUCK_Shuffle" },
	},

	["UZI"] = {
		{ "UZI_crouchfire", "UZI", "UZI_crouchfire" },
		{ "UZI_crouchreload", "UZI", "UZI_crouchreload" },
		{ "UZI_fire", "UZI", "UZI_fire" },
		{ "UZI_fire_poor", "UZI", "UZI_fire_poor" },
		{ "UZI_reload", "UZI", "UZI_reload" },
	},

	["VAN"] = {
		{ "VAN_close_back_LHS", "VAN", "VAN_close_back_LHS" },
		{ "VAN_close_back_RHS", "VAN", "VAN_close_back_RHS" },
		{ "VAN_getin_Back_LHS", "VAN", "VAN_getin_Back_LHS" },
		{ "VAN_getin_Back_RHS", "VAN", "VAN_getin_Back_RHS" },
		{ "VAN_getout_back_LHS", "VAN", "VAN_getout_back_LHS" },
		{ "VAN_getout_back_RHS", "VAN", "VAN_getout_back_RHS" },
		{ "VAN_open_back_LHS", "VAN", "VAN_open_back_LHS" },
		{ "VAN_open_back_RHS", "VAN", "VAN_open_back_RHS" },
	},

	["VENDING"] = {
		{ "VEND_Drink2_P", "VENDING", "VEND_Drink2_P" },
		{ "VEND_Drink_P", "VENDING", "VEND_Drink_P" },
		{ "vend_eat1_P", "VENDING", "vend_eat1_P" },
		{ "VEND_Eat_P", "VENDING", "VEND_Eat_P" },
		{ "VEND_Use", "VENDING", "VEND_Use" },
		{ "VEND_Use_pt2", "VENDING", "VEND_Use_pt2" },
	},

	["VORTEX"] = {
		{ "CAR_jumpin_LHS", "VORTEX", "CAR_jumpin_LHS" },
		{ "CAR_jumpin_RHS", "VORTEX", "CAR_jumpin_RHS" },
		{ "vortex_getout_LHS", "VORTEX", "vortex_getout_LHS" },
		{ "vortex_getout_RHS", "VORTEX", "vortex_getout_RHS" },
	},

	["WAYFARER"] = {
		{ "WF_Back", "WAYFARER", "WF_Back" },
		{ "WF_drivebyFT", "WAYFARER", "WF_drivebyFT" },
		{ "WF_drivebyLHS", "WAYFARER", "WF_drivebyLHS" },
		{ "WF_drivebyRHS", "WAYFARER", "WF_drivebyRHS" },
		{ "WF_Fwd", "WAYFARER", "WF_Fwd" },
		{ "WF_getoffBACK", "WAYFARER", "WF_getoffBACK" },
		{ "WF_getoffLHS", "WAYFARER", "WF_getoffLHS" },
		{ "WF_getoffRHS", "WAYFARER", "WF_getoffRHS" },
		{ "WF_hit", "WAYFARER", "WF_hit" },
		{ "WF_jumponL", "WAYFARER", "WF_jumponL" },
		{ "WF_jumponR", "WAYFARER", "WF_jumponR" },
		{ "WF_kick", "WAYFARER", "WF_kick" },
		{ "WF_Left", "WAYFARER", "WF_Left" },
		{ "WF_passenger", "WAYFARER", "WF_passenger" },
		{ "WF_pushes", "WAYFARER", "WF_pushes" },
		{ "WF_Ride", "WAYFARER", "WF_Ride" },
		{ "WF_Right", "WAYFARER", "WF_Right" },
		{ "WF_Still", "WAYFARER", "WF_Still" },
	},

	["WEAPONS"] = {
		{ "SHP_1H_Lift", "WEAPONS", "SHP_1H_Lift" },
		{ "SHP_1H_Lift_End", "WEAPONS", "SHP_1H_Lift_End" },
		{ "SHP_1H_Ret", "WEAPONS", "SHP_1H_Ret" },
		{ "SHP_1H_Ret_S", "WEAPONS", "SHP_1H_Ret_S" },
		{ "SHP_2H_Lift", "WEAPONS", "SHP_2H_Lift" },
		{ "SHP_2H_Lift_End", "WEAPONS", "SHP_2H_Lift_End" },
		{ "SHP_2H_Ret", "WEAPONS", "SHP_2H_Ret" },
		{ "SHP_2H_Ret_S", "WEAPONS", "SHP_2H_Ret_S" },
		{ "SHP_Ar_Lift", "WEAPONS", "SHP_Ar_Lift" },
		{ "SHP_Ar_Lift_End", "WEAPONS", "SHP_Ar_Lift_End" },
		{ "SHP_Ar_Ret", "WEAPONS", "SHP_Ar_Ret" },
		{ "SHP_Ar_Ret_S", "WEAPONS", "SHP_Ar_Ret_S" },
		{ "SHP_G_Lift_In", "WEAPONS", "SHP_G_Lift_In" },
		{ "SHP_G_Lift_Out", "WEAPONS", "SHP_G_Lift_Out" },
		{ "SHP_Tray_In", "WEAPONS", "SHP_Tray_In" },
		{ "SHP_Tray_Out", "WEAPONS", "SHP_Tray_Out" },
		{ "SHP_Tray_Pose", "WEAPONS", "SHP_Tray_Pose" },
	},

	["WUZI"] = {
		{ "CS_Dead_Guy", "WUZI", "CS_Dead_Guy" },
		{ "CS_Plyr_pt1", "WUZI", "CS_Plyr_pt1" },
		{ "CS_Plyr_pt2", "WUZI", "CS_Plyr_pt2" },
		{ "CS_Wuzi_pt1", "WUZI", "CS_Wuzi_pt1" },
		{ "CS_Wuzi_pt2", "WUZI", "CS_Wuzi_pt2" },
		{ "Walkstart_Idle_01", "WUZI", "Walkstart_Idle_01" },
		{ "Wuzi_follow", "WUZI", "Wuzi_follow" },
		{ "Wuzi_Greet_Plyr", "WUZI", "Wuzi_Greet_Plyr" },
		{ "Wuzi_Greet_Wuzi", "WUZI", "Wuzi_Greet_Wuzi" },
		{ "Wuzi_grnd_chk", "WUZI", "Wuzi_grnd_chk" },
		{ "Wuzi_stand_loop", "WUZI", "Wuzi_stand_loop" },
		{ "Wuzi_Walk", "WUZI", "Wuzi_Walk" },
	},
}
