NPC_SPEED_ONFOOT = {walk = 1.5559,run = 5.706,sprint = 9.562,sprintfast = 12.281}

NPC_DATAINFO_NPC		= -1
NPC_DATAINFO_TRUEDATA	= -2

NPC_DATA_BEHAVIOR_WALK_SPEED		= 1
NPC_DATA_BEHAVIOR_WEAPON_ACCURACY	= 2
NPC_DATA_TASKNUM_FIRST				= 3
NPC_DATA_TASKNUM_LAST				= 4
NPC_DATA_TASKNUM_THIS				= 5

NPC_TASK_WALK_TO_POS			= 1
NPC_TASK_WALK_ALONG_LINE		= 2
NPC_TASK_WALK_FOLLOW_ELEMENT	= 3
NPC_TASK_SHOOT_POINT			= 4
NPC_TASK_SHOOT_ELEMENT			= 5
NPC_TASK_KILL_PED				= 6

