local texturesimg = {
  {
    "img/arrow.png",  
    "arrow"
  },
  --[[{
    "img/radardraw.png",  
    "radardraw"
  },]]--
  {
    "img/radardisc.png",
    "radardisc"
  },
  {
    "img/radar_Flag.png",
    "radar_Flag"
  },
  {
    "img/radar_airYard.png",
    "radar_airYard"
  },
  {
    "img/radar_ammugun.png",
    "radar_ammugun"
  },
  {
    "img/radar_barbers.png",
    "radar_barbers"
  },
  {
    "img/radar_BIGSMOKE.png",
    "radar_BIGSMOKE"
  },
  {
    "img/radar_boatyard.png",
    "radar_boatyard"
  },
  {
    "img/radar_bulldozer.png",
    "radar_bulldozer"
  },
  {
    "img/radar_burgerShot.png",
    "radar_burgerShot"
  },
  {
    "img/radar_cash.png",
    "radar_cash"
  },
  {
    "img/radar_centre.png",
    "radar_centre"
  },
  {
    "img/radar_chicken.png",
    "radar_chicken"
  },
  {
    "img/radar_dateDisco.png",
    "radar_dateDisco"
  },
  {
    "img/radar_dateDrink.png",
    "radar_dateDrink"
  },
  {
    "img/radar_dateFood.png",
    "radar_dateFood"
  },
  {
    "img/radar_diner.png",
    "radar_diner"
  },
  {
    "img/radar_emmetGun.png",
    "radar_emmetGun"
  },
  {
    "img/radar_enemyAttack.png",
    "radar_enemyAttack"
  },
  {
    "img/radar_fire.png",
    "radar_fire"
  },
  {
    "img/radar_girlfriend.png",
    "radar_girlfriend"
  },
  {
    "img/radar_gym.png",
    "radar_gym"
  },
  {
    "img/radar_hostpital.png",
    "radar_hostpital"
  },
  {
    "img/radar_impound.png",
    "radar_impound"
  },
  {
    "img/radar_LocoSyndicate.png",
    "radar_LocoSyndicate"
  },
  {
    "img/radar_MADDOG.png",
    "radar_MADDOG"
  },
  {
    "img/radar_mafiaCasino.png",
    "radar_mafiaCasino"
  },
  {
    "img/radar_MCSTRAP.png",
    "radar_MCSTRAP"
  },
  {
    "img/radar_modGarage.png",
    "radar_modGarage"
  },
  {
    "img/radar_north.png",
    "radar_north"
  },
  {
    "img/radar_OGLOC.png",
    "radar_OGLOC"
  },
  {
    "img/radar_pizza.png",
    "radar_pizza"
  },
  {
    "img/radar_police.png",
    "radar_police"
  },
  {
    "img/radar_propertyG.png",
    "radar_propertyG"
  },
  {
    "img/radar_propertyR.png",
    "radar_propertyR"
  },
  {
    "img/radar_qmark.png",
    "radar_qmark"
  },
  {
    "img/radar_light.png",
    "radar_light"
  },
  {
    "img/radar_race.png",
    "radar_race"
  },
  {
    "img/radar_RYDER.png",
    "radar_RYDER"
  },
  {
    "img/radar_saveGame.png",
    "radar_saveGame"
  },
  {
    "img/radar_school.png",
    "radar_school"
  },
  {
    "img/radar_spray.png",
    "radar_spray"
  },
  {
    "img/radar_SWEET.png",
    "radar_SWEET"
  },
  {
    "img/radar_tattoo.png",
    "radar_tattoo"
  },
  {
    "img/radar_THETRUTH.png",
    "radar_THETRUTH"
  },
  {
    "img/radar_TORENO.png",
    "radar_TORENO"
  },
  {
    "img/radar_TorenoRanch.png",
    "radar_TorenoRanch"
  },
  {
    "img/radar_triads.png",
    "radar_triads"
  },
  {
    "img/radar_triadsCasino.png",
    "radar_triadsCasino"
  },
  {
    "img/radar_truck.png",
    "radar_truck"
  },
  {
    "img/radar_tshirt.png",
    "radar_tshirt"
  },
  {
    "img/radar_waypoint.png",
    "radar_waypoint"
  },
  {
    "img/radar_WOOZIE.png",
    "radar_WOOZIE"
  },
  {
    "img/radar_ZERO.png",
    "radar_ZERO"
  },
  {
    "img/siteM16.png",
    "siteM16"
  },
  {
    "img/siterocket.png",
    "siterocket"
  },
  {
    "img/skipicon.png",
    "skipicon"
  }
}
addEventHandler("onClientResourceStart", resourceRoot, function()
  for i = 1, #texturesimg do
    local shader = dxCreateShader("shader/shader.fx")
    engineApplyShaderToWorldTexture(shader, texturesimg[i][2])
    dxSetShaderValue(shader, "gTexture", dxCreateTexture(texturesimg[i][1]))
  end
end)
